/* The scene contains only worker-selected representations; the archive remains complete. */
const ArchivePresentation=(()=>{const status=value=>({SUPPORTED:'声明支持',CONTRADICTED:'声明反驳',UNKNOWN:'未判定',PROPOSED:'候选声明',CLUSTER:'聚合组',REVIEW_REQUIRED:'待复核',ARCHIVED_SOURCE:'已归档来源',ARCHIVED:'已归档',ARCHIVED_SNAPSHOT:'已归档快照',ARCHIVED_VERSION:'历史版本',COPIED_VERIFIED:'副本已核验',VERIFIED_WITH_SOURCE_BOUNDARIES:'来源核验有边界',EXCEEDS_8MIB:'超出旧导入范围',SOURCE_HASH_DIFFERS:'来源已变化',TENSOR_OR_TRANSPORT_ARCHIVE_NOT_IMPORTED:'归档未导入',UNREVIEWED:'未复核',INDEX_ONLY:'仅索引'}[value]||'未判定');
const shortLabel=(value,limit=28)=>{const chars=Array.from(String(value));return chars.length<=limit?chars.join(''):chars.slice(0,limit-1).join('')+'…';};
function labelIds(points,level,rect){const candidates=points.filter(p=>p.type==='cluster'&&(!rect||p.x>=rect[0]&&p.x<=rect[2]&&p.y>=rect[1]&&p.y<=rect[3])).sort((a,b)=>Number(!!b.primary)-Number(!!a.primary)||(b.count||0)-(a.count||0)||a.id.localeCompare(b.id));return new Set((level===0?candidates:candidates.slice(0,22)).map(p=>p.id));}
function screenRadius(point,level){if(point.type==='density')return point.count?Math.min(7,2+Math.log2(point.count+1)*.3):1.5;if(point.representative)return Math.min(5,2.4+Math.log2((point.degree||0)+1)*.2);const ranges=[[7,14],[5,9],[4,7]][level]||[4,12],weight=point.degree??point.count??0;return Math.min(ranges[1],ranges[0]+Math.log2(weight+1)*.35);}
function nodeStyle(point){
  if(point.type==='cluster'||point.type==='density')return {kind:'聚合',shape:'ring',color:'#9aabb9'};
  if(point.display_kind)return {kind:point.display_kind,shape:point.shape||'circle',color:point.color||'#9aabb9'};
  let type=String(point.type||'').toLowerCase();
  // Archive adapters keep the original generic type. Typed original identities
  // may supply its presentation category; arbitrary filenames cannot.
  if(type==='original_node'||type==='history_node')type=String(point.record||point.id||'').match(/:(?:owned:)?(run|receipt|fact|observation|output|artifact|hypothesis|claim):/)?.[1]||type;
  if(/hyperedge|and.rule|junction/.test(type))return {kind:'共同前提',shape:'diamond',color:'#b49bd6'};
  if(/receipt|fact/.test(type))return {kind:/fact/.test(type)?'事实':'回执',shape:'ring',color:'#99c4b3'};
  if(/observation|measurement|metric/.test(type))return {kind:'观测',shape:'circle',color:'#d4c17c'};
  if(/artifact|output|file/.test(type))return {kind:'产物',shape:'hexagon',color:'#82b9d3'};
  if(/run|execution|action/.test(type))return {kind:'执行',shape:'square',color:'#b397d0'};
  if(/project|snapshot/.test(type))return {kind:'项目快照',shape:'ring',color:'#8ca7ba'};
  if(/claim|hypothesis|statement|assertion/.test(type))return {kind:'声明',shape:'circle',color:point.primary?'#c5c8d0':'#a6a8b1'};
  return {kind:'记录',shape:'circle',color:'#9aabb9'};
}
function labelScale(scale){return 1/Math.max(1e-6,Number(scale)||1);}
function cellSize(scale,previous=0){if(!Number.isFinite(scale)||scale<=0)return 0;let size=previous>0?previous:2**Math.floor(Math.log2(20/scale));while(size*scale<12)size*=2;while(size*scale>28)size/=2;return size;}
function boundsCamera(bounds,width,height){return {x:(bounds[0]+bounds[2])/2,y:(bounds[1]+bounds[3])/2,scale:Math.min(Math.max(1,width-100)/Math.max(80,bounds[2]-bounds[0]),Math.max(1,height-120)/Math.max(80,bounds[3]-bounds[1]))*.85};}
function labelLayout(points,rect,scale,limit=60){
  const ids=new Set(),boxes=[],candidates=points.filter(p=>p.type!=='density'&&p.x>=rect[0]&&p.x<=rect[2]&&p.y>=rect[1]&&p.y<=rect[3]).sort((a,b)=>Number(!!b.primary)-Number(!!a.primary)||(b.degree||b.count||0)-(a.degree||a.count||0));
  for(const p of candidates){if(ids.size>=limit)break;const width=Math.min(210,Array.from(shortLabel(p.label)).length*13),x=p.x*scale,y=p.y*scale+20,box=[x-width/2,y,x+width/2,y+18];if(boxes.some(b=>box[0]<b[2]+8&&box[2]>b[0]-8&&box[1]<b[3]+5&&box[3]>b[1]-5))continue;boxes.push(box);ids.add(p.id);}return ids;
}
function defaults(){return {colors:true,showNames:false,nodeSize:1,edgeWidth:1,nodeBorder:1,arrows:true,textFade:0,growth:true,growthSeconds:12,showOrphans:true,membership:true,searchFilter:false,sizeMode:'degree',goal:'',nodeStyles:{},relations:{},damping:.55,flowStrength:.005,groupStrength:.025,edgeRepulsion:.15,edgeClearance:35,centerStrength:.035,repelStrength:35,linkStrength:1,linkDistance:80};}
function relationForce(family,overrides={}){return {mode:['dependency','source','history'].includes(family)?'attract':'none',strength:({dependency:1,source:.35,history:.15})[family]??1,...overrides};}
function composeEdges(edges,styleFor){
  const pairs=new Map();for(const edge of edges){const key=edge.source+'>'+edge.target;if(!pairs.has(key))pairs.set(key,[]);pairs.get(key).push(edge);}
  const composed=new Map();for(const [key,terms] of pairs){
    const ordered=terms.slice().sort((a,b)=>String(a.relationKey||a.family).localeCompare(String(b.relationKey||b.family))),first=ordered[0],styles=ordered.map(e=>({relationKey:e.relationKey,family:e.family,count:e.count,...styleFor(e)}));
    const count=ordered.reduce((n,e)=>n+e.count,0),families=new Set(ordered.map(e=>e.family)),keys=[...new Set(ordered.map(e=>e.relationKey).filter(k=>k!==undefined))];
    const channels=[0,1,2].map(i=>Math.round(styles.reduce((n,s)=>n+parseInt(s.color.slice(1+i*2,3+i*2),16)*s.count,0)/count));
    const renderStyle={...styles[0],color:'#'+channels.map(c=>c.toString(16).padStart(2,'0')).join(''),width:Math.max(...styles.map(s=>s.width)),opacity:Math.max(...styles.map(s=>s.opacity)),dash:styles.every(s=>s.dash===styles[0].dash)?styles[0].dash:'solid'};
    composed.set(key,{...first,count,family:families.size===1?first.family:'mixed',relationKey:keys.length===1?keys[0]:undefined,relationKeys:keys,relationStyles:styles,summary:ordered.some(e=>e.summary),renderStyle});
  }return composed;
}
function retainPhysics(previous,message){
  const positions=Number.isInteger(message.aggregateLevel)?new Map():previous,coords=new Float32Array(message.buffer);
  for(let i=0;i<message.ids.length;i++)positions.set(message.ids[i],{x:coords[i*2],y:coords[i*2+1]});return positions;
}
return {status,shortLabel,labelIds,screenRadius,nodeStyle,labelScale,labelLayout,defaults,cellSize,boundsCamera,relationForce,composeEdges,retainPhysics};})();
if(typeof module!=='undefined'&&module.exports)module.exports=ArchivePresentation;
if(typeof document!=='undefined')(() => {
  'use strict';
  const $=id=>document.getElementById(id),host=$('graph'),card=$('card'),results=$('results'),hover=$('hover');
  const text=(tag,value,cls)=>{const e=document.createElement(tag);e.textContent=String(value??'');if(cls)e.className=cls;return e;};
  const button=(label,action)=>{const e=text('button',label);e.addEventListener('click',action);return e;};
  const status=ArchivePresentation.status;
  const kind=value=>ArchivePresentation.nodeStyle(typeof value==='string'?{type:value}:value).kind;
  const color=p=>parseInt(ArchivePresentation.nodeStyle(p).color.slice(1),16);
  let membershipSet=new Set(),membershipEdges=new Set();let g,worker,rawWorker,rawReady=null,ready=false,paused=false,fitScale=1,level=0,seq=0,lastQuery=0,lastSignature='',pendingQuery=false,queuedView=null,selected=null,view=new Map(),searchTimer,queryTimer,viewportVersion=0;
  let topology='',showNames=false,growthFrame=null,growthIds=[],lastFrameMeasure=0,currentScene=null,nodeSize=1,edgeWidth=1,fadeTimer=null;
  let options=ArchivePresentation.defaults(),storageKey='',relationCatalog=[],relationPage=0,optionTimer=null,dragFrame=null,dragTarget=null,activeDrag=null,lastPhysics=new Map(),lastFrameAt=0,frameIntervals=[],inspectionVersion=0,initialGrowth=true;
  const relationStyles={dependency:{color:'#bebbc9',dash:'solid',width:.8,opacity:.35},source:{color:'#a9b9c8',dash:'dashed',width:.65,opacity:.16},history:{color:'#a49cb3',dash:'dotted',width:.55,opacity:.05},other:{color:'#7e838b',dash:'solid',width:.5,opacity:.08},mixed:{color:'#8e939b',dash:'solid',width:.6,opacity:.1}};
  const callbacks=new Map(),urls=[];
  const api={navigation:{mode:'spatial',scope:null,cellSize:0,history:[]},viewport:{},totals:{},physics:{},rawNode:async index=>{const n=await request('locate',{index});return n.raw_node_index===null?null:rawRequest('raw-node',n.raw_node_index??index);},rawEdge:async index=>{const e=await request('raw-locator',{index});return rawRequest('raw-edge',e.index);},rawHyperedge:id=>rawRequest('raw-hyperedge',id),locate:index=>locate(index)};
  window.RDSArchive=api;
  const shownStatus=p=>p.status_text||status(p.status);
  function persist(){try{if(storageKey)localStorage.setItem(storageKey,JSON.stringify(options));}catch{}}
  function applyForces(){persist();if(optionTimer)clearTimeout(optionTimer);optionTimer=setTimeout(()=>{optionTimer=null;const forces={};for(const k of ['damping','flowStrength','groupStrength','edgeRepulsion','edgeClearance','centerStrength','repelStrength','linkStrength','linkDistance'])forces[k]=options[k];forces.weightMode=options.sizeMode;forces.goal=options.goal;forces.membership=options.membership;forces.relations={};for(const key of Object.keys(relationStyles))forces.relations[key]=ArchivePresentation.relationForce(key,options.relations[key]);for(const r of relationCatalog)forces.relations[r.key]={...forces.relations[r.family],...options.relations[r.key]};worker.postMessage({type:'configure',options:forces});},100);}
  function reheatView(){if(paused)return;const seed=selected!==null?view.get('n'+selected):[...view.values()].find(p=>p.primary&&p.type!=='density')||[...view.values()].find(p=>p.type!=='density');if(seed)worker.postMessage({type:'reheat',id:seed.id});}
  function flushDrag(){dragFrame=null;if(!dragTarget)return;const target=dragTarget;dragTarget=null;worker.postMessage({type:'drag',...target});api.dragPackets=(api.dragPackets||0)+1;}
  function sendDrag(target){
    if(paused)return;
    if(target.x===null){if(activeDrag!==target.id)return;if(dragFrame!==null)cancelAnimationFrame(dragFrame);flushDrag();worker.postMessage({type:'drag',...target});activeDrag=null;return;}
    activeDrag=target.id;dragTarget=target;const n=g.nodeLookup.get(target.id);if(n){n.x=target.x;n.y=target.y;lastPhysics.set(target.id,{x:target.x,y:target.y});g.changed();}
    if(dragFrame===null)dragFrame=requestAnimationFrame(flushDrag);
  }
  function makeWorker(){const code=$('d3-worker-lib').textContent+'\n'+$('archive-worker').textContent,url=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));urls.push(url);return new Worker(url);}
  function request(type,value={}){return new Promise((resolve,reject)=>{const request=++seq;callbacks.set(request,{resolve,reject});worker.postMessage({type,...value,request});});}
  async function rawRequest(type,index){if(type!=='raw-hyperedge'&&(!Number.isInteger(index)||index<0))throw Error('Invalid archive index');if(!rawReady){rawReady=new Promise((resolve,reject)=>{rawWorker=makeWorker();rawWorker.onmessage=e=>{const m=e.data;if(m.type==='raw-ready')resolve();else if(m.type==='error'){const cb=callbacks.get(m.request);if(cb){callbacks.delete(m.request);cb.reject(Error(m.message));}else reject(Error(m.message));}else{const cb=callbacks.get(m.request);if(cb){callbacks.delete(m.request);cb.resolve(m.value);}}};rawWorker.postMessage({type:'raw-init',compressed:$('archive-raw').textContent});});}await rawReady;return new Promise((resolve,reject)=>{const request=++seq;callbacks.set(request,{resolve,reject});rawWorker.postMessage({type,index,id:type==='raw-hyperedge'?index:undefined,request});});}
  function replace(source,needle,value){if(!source.includes(needle))throw Error('Pinned renderer contract differs');return source.replace(needle,value);}
  function rendererSource(){let source=$('archive-renderer').textContent;
    // Connection anchors supply line geometry, never glyphs or interaction.
    // Do not use rdsHidden: that flag also hides every incident line.
    source=replace(source,'if (this.rendered || this.rdsHidden) return false;','if (this.rendered || this.rdsHidden || this.rds?.anchor) return false;');
    source=replace(source,'if(this.rdsHidden){this.circle.visible=', 'if(this.rds?.anchor)return; if(this.rdsHidden){this.circle.visible=');
    // A stroked hollow ring has no filled hit geometry in Pixi. Keep its centre
    // interactive, and return to the native filled geometry on a shape change.
    source=replace(source,'this.rdsShape=shape;c.clear();',"this.rdsShape=shape;c.hitArea=shape==='ring'?new PIXI.Circle(0,0,110):null;c.clear();");
    source=replace(source,'const t = this.text = new PIXI.Text(this.label || this.id, this.textStyle());','const t = this.text = new PIXI.Container(); t.style=this.textStyle(); t.anchor={set(){}}; t.__archiveDeferred=true;');
    source=replace(source,'const hl = r.getHighlightNode(), isHl = hl === this, ns = r.nodeScale, text = this.text;',`const labelOn=(this.rds?.labelAllowed || r.rdsPinned===this)&&r.highlightNode!==this&&r.dragNode!==this;if(this.text.__archiveDeferred && labelOn){const old=this.text,t=this.text=new PIXI.Text(this.label||this.id,this.textStyle());t.eventMode='none';t.resolution=1.5;t.anchor.set(.5,0);t.zIndex=2;t.alpha=0;r.hanger.addChild(t);old.destroy();} const hl = r.getHighlightNode(), isHl = hl === this, ns = r.nodeScale, text = this.text;`);
    // Deferred containers never become labels until the same node is readable or selected.
    source=replace(source,'let textVis = ta > 0.001 &&',"let textVis = !text.__archiveDeferred && labelOn && ta > 0.001 &&");
    source=replace(source,'clamp(this.targetScale, 1 / 128, 8)','clamp(this.targetScale, this.archiveMinScale || 1/128, this.archiveMaxScale || 8)');
    source=replace(source,'fontSize: 14 + this.getSize() / 4','fontSize: 13');
    source=replace(source,'if (isHl) ta = 1;','if (labelOn) ta = 1;');
    source=replace(source,'const nodeAlpha = this.fadeAlpha * fill.a;',"const temporal=this.rds?.fadeOut?Math.max(0,1-(performance.now()-this.rds.birth)/280):Math.min(1,Math.max(0,(performance.now()-(this.rds?.birth??-1000))/280)); const nodeAlpha=this.fadeAlpha*fill.a*temporal;");
    source=replace(source,'ta *= r.colors.text.a;','ta *= r.colors.text.a*temporal;');
    source=replace(source,'c.visible = circleVis;',"c.visible=circleVis;c.eventMode=this.rds?.ghost?'none':'static';");
    source=replace(source,'const s = isHl && r.scale < 1 ? 1 / r.scale : ns;','const s = 1/r.scale;');
    source=replace(source,'this.statusOutlineShape!==shape','this.statusOutlineShape!==shape || this.archiveBorder!==this.r.opts.nodeBorder');
    source=replace(source,'this.statusOutlineShape=shape;c.clear().lineStyle(14,0xffffff,1);','this.statusOutlineShape=shape;this.archiveBorder=this.r.opts.nodeBorder;c.clear().lineStyle(14*(this.r.opts.nodeBorder??1),0xffffff,1);');
    source=replace(source,'const hl=this.dragNode || this.highlightNode || this.rdsPinned;', 'if(this.rdsPinned && !this.dragNode && !this.highlightNode && this.archiveMembership){this.rdsLastHL=this.rdsPinned;this.rdsRelated=this.archiveMembership;return this.rdsPinned;} const hl=this.dragNode || this.highlightNode || this.rdsPinned;');source=replace(source,'if (this.rendered || !this.source.rendered || !this.target.rendered) return;','if (this.rendered) return;');source=replace(source,'if (n.rendered || n.rdsHidden) continue;','if(n.rendered || n.rdsHidden || n.rds?.anchor || outside(this.viewport,box(n.x,n.y,n.getSize()*this.nodeScale+1))) continue;');source=replace(source,'this.rds?.dash ? r.rdsDashTexture : PIXI.Texture.WHITE',"this.rds?.pattern==='dotted'?(r.archiveDotTexture||r.rdsDashTexture):this.rds?.dash ? r.rdsDashTexture : PIXI.Texture.WHITE");return source;
  }
  function camera(x,y,scale){g.targetScale=Math.min(g.archiveMaxScale||8,Math.max(g.archiveMinScale||1e-6,scale));g.setScale(g.targetScale);g.setPan(g.width/2-x*g.scale,g.height/2-y*g.scale);g.panvX=g.panvY=0;g.changed();query(true);}
  function fit(preserveNavigation=false){const b=api.bounds;if(!b)return;if(preserveNavigation!==true){api.navigation={mode:'spatial',scope:null,cellSize:0,history:[]};$('focus-back').hidden=true;clearSelection();}fitScale=Math.min((g.width-100)/Math.max(100,b[2]-b[0]),(g.height-120)/Math.max(100,b[3]-b[1]));fitScale=Math.max(1e-6,Math.min(2,fitScale*.85));g.archiveMinScale=fitScale/4;g.archiveMaxScale=Math.max(8,fitScale*24);camera((b[0]+b[2])/2,(b[1]+b[3])/2,fitScale);}
  function currentLevel(){if(api.navigation)return Number.isInteger(api.navigation.mode)?api.navigation.mode:3;const ratio=g.scale/fitScale;return ratio<2?0:ratio<5?1:ratio<12?2:3;}
  function sendView(next){
    pendingQuery=true;lastSignature=next.signature;lastQuery=performance.now();const version=++viewportVersion;
    request('viewport',{level:next.level,rect:next.rect,edgeBudget:next.level===0?3500:800,nodeBudget:3500,filters:next.filters}).then(m=>{
      pendingQuery=false;
      // Keep completed scenes visible during continuous panning, then query the
      // newest camera. Coalescing must bound work without starving the display.
      if(version===viewportVersion&&!m.cancelled){api.viewport={...m.counters,level:m.level+1,queryMs:performance.now()-next.started};paint(m,next.rect);if(initialGrowth){initialGrowth=false;if(options.growth)grow();}}
      if(queuedView){const latest=queuedView;queuedView=null;sendView(latest);}
    }).catch(error=>{pendingQuery=false;queuedView=null;fail(error);});
  }
  function query(force=false){
    if(!ready)return;const now=performance.now(),scale=g.scale,halo=80/scale,rect=[-g.panX/scale-halo,-g.panY/scale-halo,(g.width-g.panX)/scale+halo,(g.height-g.panY)/scale+halo];level=currentLevel();const filters={showOrphans:options.showOrphans,membership:options.membership,query:options.searchFilter?$('search').value.trim():''};if(api.navigation){filters.scope=api.navigation.scope;filters.selected=selected;if(level===3)filters.cellSize=api.navigation.cellSize=ArchivePresentation.cellSize(scale,api.navigation.cellSize);}const signature=JSON.stringify([level,...rect.map(v=>Math.round(v*scale/4)),filters]);
    if(signature===lastSignature&&!force){queuedView=null;return;}
    const next={level,rect,signature,filters,started:now};
    if(pendingQuery){queuedView=next;return;}
    if(!force&&now-lastQuery<70){if(!queryTimer)queryTimer=setTimeout(()=>{queryTimer=null;query();},70);return;}
    if(queryTimer){clearTimeout(queryTimer);queryTimer=null;}sendView(next);
  }
  function pattern(dotted){const canvas=document.createElement('canvas');canvas.width=16;canvas.height=4;const c=canvas.getContext('2d');c.fillStyle='#fff';if(dotted){c.beginPath();c.arc(2,2,1.5,0,Math.PI*2);c.fill();}else c.fillRect(0,1,9,2);return PIXI.Texture.from(canvas);}
  let dashTexture,dotTexture;
  function pointStyle(p){const base=ArchivePresentation.nodeStyle(p),custom=options.nodeStyles[base.kind]||{};return {...base,...custom,color:options.colors?(custom.color||base.color):'#b5b8be'};}
  function edgeStyle(e){const style={...(relationStyles[e.family]||relationStyles.other),...(options.relations[e.family]||{}),...(options.relations[e.relationKey]||{})};return e.summary?{...style,width:Math.min(1,style.width),opacity:Math.min(.12,style.opacity),dash:'solid'}:style;}
  function restoreEdges(){for(const l of g.links){if(l.archiveStyle)l.rds={...l.archiveStyle};}g.rdsLastHL=undefined;g.changed();}
  function clearSelection(){inspectionVersion++;selected=null;membershipSet=new Set();membershipEdges=new Set();g.archiveMembership=membershipSet;g.rdsPinned=null;restoreEdges();}
  function paint(m,rect){
    if(fadeTimer!==null){clearTimeout(fadeTimer);fadeTimer=null;}
    const previous=currentScene;currentScene={m,rect};const installed=currentScene,started=performance.now(),screenRect=[-g.panX/g.scale,-g.panY/g.scale,(g.width-g.panX)/g.scale,(g.height-g.panY)/g.scale];
    const labels=showNames&&g.scale/fitScale>=options.textFade?ArchivePresentation.labelLayout(m.points,screenRect,g.scale):new Set();
    const incoming=new Set(m.points.map(p=>p.id)),oldNodes=g.nodeLookup,ghosts=previous&&activeDrag===null?previous.m.points.filter(p=>!incoming.has(p.id)&&oldNodes.has(p.id)).slice(0,Math.max(0,3500-m.points.length)).map(p=>({...p,x:oldNodes.get(p.id).x,y:oldNodes.get(p.id).y,id:'ghost:'+p.id,ghost:true,fadeOut:true})):[];
    const scenePoints=[...m.points,...(m.anchors||[]),...ghosts],nodes=Object.create(null),links=[];view=new Map(m.points.map(p=>[p.id,p]));for(const p of scenePoints){if(p.anchor){nodes[p.id]={label:'',type:'',rds:{anchor:true,radius:0}};continue;}const style=pointStyle(p),weight=p.goal_weights?.[options.goal],radius=options.sizeMode==='uniform'?4:options.sizeMode==='goal'&&Number.isFinite(weight)?4+10*Math.sqrt(Math.max(0,Math.min(1,weight))):ArchivePresentation.screenRadius(p,m.level);nodes[p.id]={label:p.ghost?'':p.type==='cluster'?ArchivePresentation.shortLabel(p.label,16)+' · '+p.count:ArchivePresentation.shortLabel(p.label,16),type:'',color:{rgb:parseInt(style.color.slice(1),16),a:p.type==='density'?.55:p.raw&&!p.primary?.72:1},rds:{...p,birth:p.ghost?started:oldNodes.get(p.id)?.rds?.birth??started,record:p.record||p.id,labelAllowed:!p.ghost&&labels.has(p.id),radius:p.representative||p.type==='density'||p.type==='cluster'?radius/Math.sqrt(g.scale):radius,outline:p.outline?.state!=='neutral'&&options.nodeBorder>0?p.outline:undefined,size:style.size||1,shape:style.shape}};}
    if(ghosts.length&&typeof setTimeout!=='undefined')fadeTimer=setTimeout(()=>{fadeTimer=null;if(ready&&currentScene===installed)paint(m,rect);},300);
    // The pinned renderer has one line per endpoint pair. Preserve each original
    // relation style and blend its colour by multiplicity, independent of order.
    const pairs=ArchivePresentation.composeEdges(m.edges,edgeStyle);
    for(const e of pairs.values()){const style=e.renderStyle;links.push([e.source,e.target,{relation:e.family,relationKey:e.relationKey,relationKeys:e.relationKeys,relationStyles:e.relationStyles,dash:style.dash!=='solid',pattern:style.dash,arrow:options.arrows&&e.family==='dependency'&&!e.summary,summary:!!e.summary,width:style.width,opacity:style.opacity,count:e.count,color:style.color}]);}
    const signature=m.level+'|'+scenePoints.map(p=>p.id).join(',')+'|'+links.map(l=>l[0]+'>'+l[1]+':'+l[2].relation+':'+l[2].count).join(',');
    if(signature!==topology){g.setData({nodes,links});topology=signature;api.setDataCalls=(api.setDataCalls||0)+1;}
    for(const p of scenePoints){const n=g.nodeLookup.get(p.id);if(n){const position=lastPhysics.get(p.id)||p;n.x=position.x;n.y=position.y;n.color=nodes[p.id].color;n.label=nodes[p.id].label;n.rds=nodes[p.id].rds;if(growthFrame!==null&&!p.anchor)n.rdsHidden=growthIds.includes(p.id);if(n.text&&!n.text.__archiveDeferred)n.text.text=n.label;}}
    g.rdsPinned=selected!==null?g.nodeLookup.get('n'+selected)||null:null;g.rdsLastHL=undefined;
    for(const l of g.links){const edge=pairs.get(l.source.id+'>'+l.target.id),style=edge?.renderStyle;if(style){l.rds={...(l.rds||{}),color:style.color,width:style.width,opacity:style.opacity,dash:style.dash!=='solid',pattern:style.dash,relation:edge.family,relationKey:edge.relationKey,relationKeys:edge.relationKeys,relationStyles:edge.relationStyles,arrow:options.arrows&&edge.family==='dependency'&&!edge.summary,summary:!!edge.summary};l.archiveStyle={...l.rds};}if(l.rendered&&style)l.line.texture=style.dash==='dotted'?dotTexture:style.dash==='dashed'?dashTexture:PIXI.Texture.WHITE;if(selected!==null&&(l.source.id==='n'+selected||l.target.id==='n'+selected))l.rds={...l.rds,color:'#b8cbd7',width:2};}
    g.changed();for(const [k,v] of Object.entries(api.viewport))host.dataset[k]=String(v);host.dataset.transitionGlyphs=String(ghosts.length);host.dataset.defaultLabels=String(labels.size);host.dataset.totalNodes=String(api.totals.nodes);host.dataset.totalEdges=String(api.totals.edges);host.dataset.lod=String(m.level+1);
    $('state').textContent='';
    $('view-counts').textContent=m.level<3?['研究组','来源','分块'][m.level]+' · '+m.counters.visibleNodes+' 个聚合':m.counters.visibleNodes.toLocaleString()+' 条记录'+(m.counters.nodeAggregation?' · 聚合显示':'');
    document.querySelectorAll('#layers button').forEach(b=>b.classList.toggle('active',Number(b.dataset.level)===m.level));api.paintMs=performance.now()-started;host.dataset.paintMs=String(api.paintMs);paintLegend();
  }
  function cancelGrowth(){if(growthFrame!==null)cancelAnimationFrame(growthFrame);growthFrame=null;for(const id of growthIds){const n=g?.nodeLookup.get(id);if(n)n.rdsHidden=false;}growthIds=[];if($('growth-progress'))$('growth-progress').textContent='';}
  function grow(){
    cancelGrowth();if(!options.growth)return;growthIds=[...view.values()].sort((a,b)=>(a.flow_level??0)-(b.flow_level??0)||Number(!!b.primary)-Number(!!a.primary)||(b.degree||b.count||0)-(a.degree||a.count||0)||a.id.localeCompare(b.id)).map(p=>p.id);const ids=[...growthIds],start=performance.now(),count=ids.length;
    for(const id of growthIds){const n=g.nodeLookup.get(id);if(n)n.rdsHidden=true;}
    let shown=0;function reveal(now){const end=Math.min(count,Math.max(1,Math.floor(count*(now-start)/(options.growthSeconds*1000))));while(shown<end){const id=ids[shown++],n=g.nodeLookup.get(id);if(n)n.rdsHidden=false;}growthIds=ids.slice(shown);if($('growth-progress'))$('growth-progress').textContent=Math.round(shown/count*100)+'%';g.changed();if(shown<count)growthFrame=requestAnimationFrame(reveal);else{growthFrame=null;growthIds=[];if($('growth-progress'))$('growth-progress').textContent='';}}growthFrame=requestAnimationFrame(reveal);
  }
  function appearance(){persist();showNames=options.showNames;nodeSize=options.nodeSize;edgeWidth=options.edgeWidth;g.setOptions({nodeSize,lineSize:edgeWidth,textFade:0,nodeBorder:options.nodeBorder,showArrow:options.arrows});if(currentScene)paint(currentScene.m,currentScene.rect);paintLegend();}
  function paintLegend(){const row=text('div','','legend-row'),shapes={circle:'●',ring:'○',square:'■',diamond:'◇',triangle:'▲',hexagon:'⬡'};const kinds=[...new Set((currentScene?.m.points||[]).filter(p=>p.type!=='cluster'&&p.type!=='density').map(p=>pointStyle(p).kind))];for(const k of (kinds.length?kinds:['声明','执行','回执','产物','观测','共同前提'])){const sample=currentScene?.m.points.find(p=>pointStyle(p).kind===k),st=options.nodeStyles[k]||(sample&&pointStyle(sample)),chip=text('span'),symbol=text('i',shapes[st?.shape]||'●','symbol');symbol.style.color=options.colors?st?.color:'#b5b8be';chip.append(symbol,text('span',k==='超边'?'共同前提':k));row.append(chip);}const statusRow=text('div','','legend-row legend-note');for(const [c,label] of [['#39b872','成功 / 支持'],['#e65b63','失败 / 反驳'],['#9299a6','未判定']]){const chip=text('span'),symbol=text('i','○','symbol');symbol.style.color=c;chip.append(symbol,text('span',label));statusRow.append(chip);}$('legend').replaceChildren(row,statusRow);}
  function section(label,id){const e=text('details'),head=text('summary',label),body=text('div');e.id=id;body.className='controls-section';e.append(head,body);$('extra-controls').append(e);return body;}
  function checkbox(parent,label,key,action=appearance){const row=text('label','','display-option'),input=text('input');input.type='checkbox';input.checked=!!options[key];input.setAttribute('aria-label',label);input.addEventListener('change',()=>{options[key]=input.checked;persist();action();});row.append(input,text('span',label));parent.append(row);return input;}
  function slider(parent,label,key,min,max,step,action=appearance,obj=options){const row=text('label','','display-option'),caption=text('span',label),out=text('output',obj[key]),input=text('input');input.type='range';input.min=min;input.max=max;input.step=step;input.value=obj[key];input.setAttribute('aria-label',label);row.append(caption,out);parent.append(row,input);input.addEventListener('input',()=>{obj[key]=Number(input.value);out.textContent=input.value;action();});return input;}
  function select(parent,label,current,entries,action){const row=text('label','','display-option'),input=text('select');input.setAttribute('aria-label',label);for(const [value,caption] of entries){const o=text('option',caption);o.value=value;input.append(o);}input.value=current;input.addEventListener('change',()=>action(input.value));row.append(text('span',label),input);parent.append(row);return input;}
  function settingsUI(){
    const kinds={'声明':['#c2c8d2','circle'],'执行':['#b39ddb','square'],'回执':['#82c4af','ring'],'事实':['#82c4af','ring'],'产物':['#82b6d4','hexagon'],'观测':['#d5c17e','circle'],'超边':['#9c95af','diamond'],'共同前提':['#9c95af','diamond'],'项目快照':['#8aa1b8','ring'],'聚合':['#9aabb9','ring'],'记录':['#9aabb9','circle'],'来源':['#8ca7ba','ring'],'历史版本':['#8ca7ba','ring'],'证据':['#99c4b3','ring'],'知识':['#82b9d3','hexagon'],'实验':['#b397d0','square'],'执行尝试':['#b397d0','square']};
    for(const [k,[color,shape]] of Object.entries(kinds))options.nodeStyles[k]={color,shape,size:1,...options.nodeStyles[k]};
    $('show-names').checked=options.showNames;$('node-size').value=options.nodeSize;$('edge-width').value=options.edgeWidth;
    const back=button('返回上层',()=>returnFocus());back.id='focus-back';back.hidden=true;($('fit').parentElement||$('tools')).append(back);
    const filters=section('筛选','filter-settings');checkbox(filters,'显示孤立节点','showOrphans',()=>query(true));checkbox(filters,'显示归属关系','membership',()=>{applyForces();query(true);});checkbox(filters,'搜索时筛选图谱','searchFilter',()=>query(true));
    const display=section('显示与生长','display-settings');checkbox(display,'按类型着色','colors');checkbox(display,'结论箭头','arrows');checkbox(display,'缓慢生长','growth',()=>{persist();if(!options.growth){cancelGrowth();g.changed();}});slider(display,'标签阈值','textFade',0,16,.5);slider(display,'节点描边','nodeBorder',0,3,.25);slider(display,'生长时长（秒）','growthSeconds',4,30,1,()=>persist());display.append(button('跳过生长',()=>{cancelGrowth();g.changed();}));
    const goals=api.goals||[],sizes=[['degree','连接度'],['uniform','统一大小']];if(goals.length){sizes.push(['goal','目标结构权重']);if(!goals.some(g=>g.id===options.goal))options.goal=goals[0].id;}if(options.sizeMode==='goal'&&!goals.length)options.sizeMode='degree';select(display,'大小依据',options.sizeMode,sizes,v=>{options.sizeMode=v;appearance();applyForces();});if(goals.length)select(display,'研究目标',options.goal,goals.map(goal=>[goal.id,goal.label]),v=>{options.goal=v;appearance();applyForces();});
    const nodes=section('节点样式','node-style-settings');for(const [k,st] of Object.entries(options.nodeStyles)){const row=text('div','','style-row'),picker=text('input');picker.type='color';picker.value=st.color;picker.setAttribute('aria-label',k+'颜色');picker.addEventListener('input',()=>{st.color=picker.value;appearance();});row.append(text('span',k),picker);nodes.append(row);select(nodes,k+'形状',st.shape,[['circle','圆点'],['ring','圆环'],['square','方形'],['diamond','菱形'],['triangle','三角'],['hexagon','六边形']],v=>{st.shape=v;appearance();});slider(nodes,k+'大小','size',.5,2,.1,appearance,st);}
    const forces=section('力学','force-settings');for(const [caption,key,min,max,step] of [['运动阻尼','damping',.1,.85,.05],['依赖流向','flowStrength',0,.08,.005],['同次执行凝聚','groupStrength',0,.15,.005],['超边排斥','edgeRepulsion',0,.6,.025],['超边留白','edgeClearance',15,100,5],['向心力','centerStrength',0,.3,.005],['节点排斥','repelStrength',1,3000,1],['节点吸引','linkStrength',0,2,.05],['连线距离','linkDistance',40,400,5]])slider(forces,caption,key,min,max,step,applyForces);
    forces.append(button('重新布局',reheatView));
    const relations=section('关系样式与力学','relation-settings'),catalog=[...Object.keys(relationStyles).map(key=>({key,label:({dependency:'依赖',source:'来源 / 归属',history:'历史',other:'其他',mixed:'混合'})[key],family:key})),...relationCatalog];
    function renderRelations(){relations.replaceChildren();for(const r of catalog.slice(relationPage*12,relationPage*12+12)){const base=relationStyles[r.family]||relationStyles.other,st={...base,...ArchivePresentation.relationForce(r.family,options.relations[r.family]),...options.relations[r.key]},label=r.label||r.type||r.semantic,change=(key,value,action)=>{options.relations[r.key]={...options.relations[r.key],[key]:value};action();};relations.append(text('h3',label));select(relations,label+'作用',st.mode,[['attract','吸引'],['repel','排斥'],['none','无力']],v=>change('mode',v,applyForces));slider(relations,label+'强度','strength',0,2,.1,()=>change('strength',st.strength,applyForces),st);const picker=text('input');picker.type='color';picker.value=st.color;picker.setAttribute('aria-label',label+'颜色');picker.addEventListener('input',()=>change('color',picker.value,appearance));relations.append(picker);slider(relations,label+'粗细','width',.3,3,.1,()=>change('width',st.width,appearance),st);select(relations,label+'线型',st.dash,[['solid','实线'],['dashed','虚线'],['dotted','点线']],v=>change('dash',v,appearance));if(r.key!==r.family)relations.append(button('继承分类设置',()=>{delete options.relations[r.key];appearance();applyForces();renderRelations();}));}if(catalog.length>12)pager(relations,relationPage,catalog.length,12,p=>{relationPage=p;renderRelations();});}renderRelations();appearance();applyForces();
  }
  function restoreSettings(source){
    storageKey='rds-archive-v2:'+source.raw_sha256;let saved=null;try{saved=JSON.parse(localStorage.getItem(storageKey)||localStorage.getItem('rds-replica-v2:'+source.raw_sha256)||'null');}catch{}
    if(!saved||typeof saved!=='object')return;
    const ranges={nodeSize:[.5,2],edgeWidth:[.3,3],nodeBorder:[0,3],textFade:[0,16],growthSeconds:[4,30],damping:[.1,.85],flowStrength:[0,.08],groupStrength:[0,.15],edgeRepulsion:[0,.6],edgeClearance:[15,100],centerStrength:[0,.3],repelStrength:[1,3000],linkStrength:[0,2],linkDistance:[40,400]};
    for(const [k,[lo,hi]] of Object.entries(ranges))if(Number.isFinite(saved[k]))options[k]=Math.max(lo,Math.min(hi,saved[k]));
    for(const k of ['colors','showNames','arrows','growth','showOrphans','membership','searchFilter'])if(typeof saved[k]==='boolean')options[k]=saved[k];
    if(['degree','uniform','goal'].includes(saved.sizeMode))options.sizeMode=saved.sizeMode;if(typeof saved.goal==='string'&&(api.goals||[]).some(g=>g.id===saved.goal))options.goal=saved.goal;
    const shapes=['circle','ring','square','diamond','triangle','hexagon'];
    for(const [k,st] of Object.entries(saved.nodeStyles||{}).slice(0,32)){if(!st||typeof st!=='object')continue;const value={};if(/^#[0-9a-f]{6}$/i.test(st.color))value.color=st.color;if(shapes.includes(st.shape))value.shape=st.shape;if(Number.isFinite(st.size))value.size=Math.max(.5,Math.min(2,st.size));options.nodeStyles[k]=value;}
    const keys=new Set([...Object.keys(relationStyles),...relationCatalog.map(r=>r.key)]);
    const migrated={...saved.relations};for(const r of relationCatalog)if(r.legacyKey&&!keys.has(r.legacyKey)&&Object.hasOwn(migrated,r.legacyKey)&&!Object.hasOwn(migrated,r.key))migrated[r.key]=migrated[r.legacyKey];
    for(const [k,st] of Object.entries(migrated)){if(!keys.has(k)||!st||typeof st!=='object')continue;const value={};if(/^#[0-9a-f]{6}$/i.test(st.color))value.color=st.color;if(['solid','dashed','dotted'].includes(st.dash))value.dash=st.dash;if(['attract','repel','none'].includes(st.mode))value.mode=st.mode;for(const [key,lo,hi] of [['strength',0,2],['width',.3,3],['opacity',0,1]])if(Number.isFinite(st[key]))value[key]=Math.max(lo,Math.min(hi,st[key]));options.relations[k]=value;}
  }
  function toggleSettings(open){const panel=$('tools');panel.hidden=typeof open==='boolean'?!open:!panel.hidden;for(const id of ['settings','gear'])$(id).setAttribute('aria-expanded',String(!panel.hidden));}
  function pager(parent,page,total,size,action){const nav=text('div','', 'pager');nav.append(button('上一页',()=>action(Math.max(0,page-1))),text('span',(page+1)+' / '+Math.max(1,Math.ceil(total/size))),button('下一页',()=>action(Math.min(Math.max(0,Math.ceil(total/size)-1),page+1))));nav.firstChild.disabled=page===0;nav.lastChild.disabled=(page+1)*size>=total;parent.append(nav);}
  async function inspect(index,page=0){const version=++inspectionVersion,m=await request('detail',{index,page});if(version!==inspectionVersion)return;restoreEdges();selected=index;g.rdsPinned=g.nodeLookup.get('n'+index)||null;g.rdsLastHL=undefined;g.changed();if(api.navigation)query(true);card.hidden=false;card.replaceChildren(button('×',()=>{card.hidden=true;clearSelection();}),text('h2',m.node.label),text('span',kind(m.node),'tag'),text('span',shownStatus(m.node),'tag'));if(m.node.primary)card.append(text('span','当前记录','tag'));if(m.node.summary&&m.node.summary!==m.node.label)card.append(text('p',m.node.summary));card.append(text('h3',/hyperedge/i.test(m.node.type)?'共同前提与结论 · '+m.total:'关联记录 · '+m.total));
    let lastGroup='';for(const entry of m.entries){const row=text('div','', 'relation-row');const relation=/premise|共同前提/i.test(entry.type)?'共同前提':/conclusion|结论/i.test(entry.type)?'结论':entry.direction==='out'?'指向':'来自';if(relation!==lastGroup&&/共同前提|结论/.test(relation)){card.append(text('h3',relation));lastGroup=relation;}row.append(button(entry.label,()=>locate(entry.index)),text('small',relation+' · '+shownStatus(entry)));card.append(row);}if(m.total>m.size)pager(card,m.page,m.total,m.size,p=>inspect(index,p));
    // Complete membership is queried independently of the paginated card.
    const membership=await request('highlight',{index});if(version!==inspectionVersion)return;g.rdsRelated=new Set(membership.nodes.map(i=>'n'+i));api.selection={index,totalMembers:membership.nodes.length,totalEdges:membership.edges.length};membershipSet=new Set(membership.nodes.map(i=>'n'+i));membershipEdges=new Set(membership.edges);g.rdsLastHL=g.rdsPinned;g.rdsRelated=membershipSet;g.archiveMembership=membershipSet;for(const l of g.links)if(l.source.id==='n'+index||l.target.id==='n'+index){l.rds={...(l.rds||{}),color:'#b8cbd7',width:2};}g.changed();
  }
  async function locate(index){const m=await request('locate',{index});api.navigation.mode='spatial';api.navigation.scope=null;camera(m.x,m.y,Math.max(.8,fitScale*18));await inspect(index);}
  function viewFilters(){return {membership:options.membership,showOrphans:options.showOrphans,query:options.searchFilter?$('search').value.trim():''};}
  async function focusCluster(index){const m=await request('cluster',{index,filters:viewFilters()});if(!m.total)return;const nav=api.navigation;nav.history.push({mode:nav.mode,scope:nav.scope,x:(g.width/2-g.panX)/g.scale,y:(g.height/2-g.panY)/g.scale,scale:g.scale});nav.mode='spatial';nav.scope=index;nav.cellSize=0;clearSelection();card.hidden=true;const target=ArchivePresentation.boundsCamera(m.memberBounds,g.width,g.height);camera(target.x,target.y,target.scale);$('focus-back').hidden=false;}
  function returnFocus(){const nav=api.navigation,prior=nav.history.pop();clearSelection();nav.mode=prior?.mode??'spatial';nav.scope=prior?.scope??null;nav.cellSize=0;if(prior)camera(prior.x,prior.y,prior.scale);else fit();$('focus-back').hidden=!nav.history.length;}
  async function cluster(index){clearSelection();const m=await request('cluster',{index,filters:viewFilters()}),c=m.cluster;card.hidden=false;const expand=button('展开此组',()=>focusCluster(index).catch(fail));expand.disabled=!m.total;card.replaceChildren(button('×',()=>card.hidden=true),text('h2',c.label),text('p',m.total+' 条可见记录 · 共 '+c.node_count+' 条'),expand);}
  async function density(point,page=0){const m=await request('cell-members',{cell:point.cell,filters:{...viewFilters(),scope:api.navigation.scope,selected},page});card.hidden=false;card.replaceChildren(button('×',()=>card.hidden=true),text('h2','附近记录 · '+m.total));for(const entry of m.entries){const row=button(entry.label,()=>locate(entry.index).catch(fail));row.append(text('small',kind(entry)+' · '+shownStatus(entry)));card.append(row);}if(m.total>m.size)pager(card,m.page,m.total,m.size,p=>density(point,p).catch(fail));}
  async function search(page=0){const queryText=$('search').value.trim();if(options.searchFilter)query(true);if(!queryText){results.hidden=true;return;}const m=await request('search',{query:queryText,page});if(queryText!==$('search').value.trim())return;results.hidden=false;results.replaceChildren(text('small',m.total+' 条匹配'));for(const n of m.entries){const row=button(n.label,()=>locate(n.index));row.append(text('small',kind(n)+' · '+shownStatus(n)));results.append(row);}if(m.total>m.size)pager(results,m.page,m.total,m.size,search);}
  function fail(error){$('state').textContent='暂时无法读取图谱';host.dataset.error=String(error?.message||error);console.error(error);}
  async function init(){try{Function(rendererSource())();g=new window.GraphRenderer(host,function(){self.onmessage=()=>{};});const nativeHandler=g.worker.onmessage;g.worker.terminate();worker=makeWorker();g.worker={onmessage:nativeHandler,postMessage:m=>{if(m.forceNode)sendDrag(m.forceNode);},terminate(){}};g.setOptions({nodeSize:1,lineSize:1,textFade:0,nodeBorder:1,showArrow:true});dashTexture=pattern(false);dotTexture=pattern(true);g.archiveDotTexture=dotTexture;
      const down=g.onPointerDown.bind(g);g.onPointerDown=(n,e)=>{const p=view.get(n.id);if(!p)return;if(paused){e.stopPropagation();g.onNodeClick(n);return;}if(p.raw||p.type==='cluster')down(n,e);else g.onNodeClick(n);};g.onNodeClick=n=>{const p=view.get(n.id);if(!p)return;if(p.zoomOnly){const target=ArchivePresentation.boundsCamera(p.bounds||[p.x,p.y,p.x,p.y],g.width,g.height);api.navigation.mode='spatial';camera(target.x,target.y,Math.max(g.scale*1.3,target.scale));if(p.cell&&p.id.startsWith('v3:'))density(p).catch(fail);}else if(p.raw)inspect(p.index).catch(fail);else cluster(p.index).catch(fail);};g.onNodeHover=n=>{const p=n&&view.get(n.id);if(!p){hover.hidden=true;return;}hover.hidden=false;hover.replaceChildren(text('strong',p.label),text('small',p.raw?shownStatus(p):p.type==='cluster'?p.count+' 条记录':p.count+' 条附近记录'));};
      host.addEventListener('pointermove',e=>{hover.style.left=Math.min(e.clientX+14,innerWidth-240)+'px';hover.style.top=Math.min(e.clientY+14,innerHeight-75)+'px';});
      const nativeFrame=g.frame.bind(g);g.frame=()=>{const started=performance.now();if(lastFrameAt){frameIntervals.push(started-lastFrameAt);if(frameIntervals.length>120)frameIntervals.shift();}lastFrameAt=started;nativeFrame();if(started-lastFrameMeasure>500){api.frameMs=performance.now()-started;const sorted=[...frameIntervals].sort((a,b)=>a-b),labels=g.nodes.filter(n=>n.text&&!n.text.__archiveDeferred&&n.text.visible);api.frameStats={samples:sorted.length,p50:sorted[Math.floor(sorted.length*.5)]||0,p95:sorted[Math.floor(sorted.length*.95)]||0,max:sorted.at(-1)||0};api.labels={count:labels.length,maxScreenPx:Math.max(0,...labels.map(n=>n.text.style.fontSize*n.text.scale.x*g.scale))};host.dataset.frameMs=String(api.frameMs);host.dataset.labelScreenPx=String(api.labels.maxScreenPx);host.dataset.frameP95=String(api.frameStats.p95);lastFrameMeasure=started;}query();};
      worker.onmessage=e=>{const m=e.data;if(m.request&&callbacks.has(m.request)){const cb=callbacks.get(m.request);callbacks.delete(m.request);m.type==='error'?cb.reject(Error(m.message)):cb.resolve(m);return;}if(m.type==='progress')$('state').textContent='正在准备图谱…';else if(m.type==='ready'){ready=true;api.totals={nodes:m.source.node_count,edges:m.source.edge_count};api.bounds=m.bounds;api.levels=m.levels;api.indexStats=m.indexStats;api.goals=(m.goals||[]).map(goal=>typeof goal==="string"?{id:goal,label:ArchivePresentation.shortLabel(goal)}:goal);relationCatalog=m.relationCatalog||[];restoreSettings(m.source);settingsUI();$('source-name').textContent=m.source.title||'本地档案 · 只读';$('totals').textContent=m.source.node_count.toLocaleString()+' 条记录 · '+m.source.edge_count.toLocaleString()+' 条关联';$('state').textContent='';fit();}else if(m.type==='configured'){api.forces=m.options;}else if(m.type==='physics'){api.physics={nodes:m.nodes,edges:m.edges,springs:m.springs,steps:m.steps,settled:m.settled};host.dataset.physicsNodes=String(m.nodes||0);host.dataset.physicsSteps=String(m.steps||0);if(m.buffer){lastPhysics=ArchivePresentation.retainPhysics(lastPhysics,m);if(m.clusterShifts?.length){const shifts=new Map(m.clusterShifts.map(s=>[s.index,s]));for(const p of view.values()){const s=shifts.get(p.clusterPath?.[m.aggregateLevel]);if(s){lastPhysics.set(p.id,{x:p.x+s.dx,y:p.y+s.dy});const n=g.nodeLookup.get(p.id);if(n){n.x=p.x+s.dx;n.y=p.y+s.dy;}}}}g.worker.onmessage({data:{ids:m.ids,buffer:m.buffer}});}}else if(m.type==='index-progress'){api.physics.indexRemaining=m.remaining;host.dataset.indexRemaining=String(m.remaining);}else if(m.type==='bounds-updated'){api.bounds=m.bounds;host.dataset.bounds=JSON.stringify(m.bounds);}else if(m.type==='positions-updated'){lastPhysics.clear();query(true);}else if(m.type==='error')fail(Error(m.message));};
      worker.postMessage({type:'init',compressed:$('archive-data').textContent});$('fit').addEventListener('click',fit);
      $('restart').addEventListener('click',()=>{cancelGrowth();card.hidden=true;results.hidden=true;clearSelection();api.navigation={mode:'spatial',scope:null,cellSize:0,history:[]};$('focus-back').hidden=true;fit();reheatView();});
      $('grow').addEventListener('click',grow);
      $('pause').addEventListener('click',()=>{paused=!paused;const label=paused?'恢复布局':'暂停布局';$('pause').textContent=paused?'▷':'Ⅱ';$('pause').setAttribute('aria-pressed',String(paused));$('pause').setAttribute('aria-label',label);$('pause').title=label;if(paused){if(dragFrame!==null)cancelAnimationFrame(dragFrame);dragFrame=null;dragTarget=null;activeDrag=null;}worker.postMessage({type:paused?'pause':'resume'});});
      $('theme').addEventListener('click',()=>{const light=document.body.classList.toggle('theme-light');document.body.classList.toggle('theme-dark',!light);g.readColors();g.changed();});
      for(const id of ['settings','gear'])$(id).addEventListener('click',()=>toggleSettings());
      $('show-names').addEventListener('change',()=>{options.showNames=$('show-names').checked;appearance();});
      for(const [id,key] of [['node-size','nodeSize'],['edge-width','edgeWidth']])$(id).addEventListener('input',()=>{options[key]=Number($(id).value);appearance();});
      $('search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>search().catch(fail),160);});document.querySelectorAll('#layers button').forEach(b=>b.addEventListener('click',()=>{const selectedLevel=Number(b.dataset.level);api.navigation={mode:selectedLevel===3?'spatial':selectedLevel,scope:null,cellSize:0,history:[]};$('focus-back').hidden=true;clearSelection();fit(true);}));addEventListener('resize',()=>query(true));
      addEventListener('keydown',e=>{if(e.key==='Escape')toggleSettings(false);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();toggleSettings(true);$('search').focus();}});
      addEventListener('pagehide',()=>{cancelGrowth();ready=false;if(dragFrame!==null)cancelAnimationFrame(dragFrame);worker.terminate();rawWorker?.terminate();for(const u of urls)URL.revokeObjectURL(u);URL.revokeObjectURL(g.workerBlobUrl);clearTimeout(queryTimer);clearTimeout(searchTimer);clearTimeout(optionTimer);clearTimeout(fadeTimer);callbacks.clear();queuedView=null;g.app.destroy(true,{children:true});},{once:true});
    }catch(error){fail(error);}}
  init();
})();
