'use strict';
const assert=require('node:assert/strict');
const Core=require('../scripts/hypergraph_archive/worker.js');
let cases=0;function check(name,fn){fn();cases++;console.log('PASS '+name);}
function fixture(n=80){const nodes=Array.from({length:n},(_,i)=>({id:i===0?'__proto__':'record:'+i,label:'记录 '+i,summary:i===2?'历史用途':'',type:i===1?'hyperedge':'claim',status:i===2?'CONTRADICTED':i===3?'SUPPORTED':'UNKNOWN',group:i<n/2?'A':'B',source_id:'source',primary:i===0,x:(i-n/2)*56,y:i%2?100:-100,parent:i<n/2?2:5}));const clusters=[];for(let g=0;g<2;g++){const indices=nodes.map((_,i)=>i).filter(i=>g===0?i<n/2:i>=n/2),x=g===0?-600:600;for(let level=0;level<3;level++)clusters.push({id:'c'+clusters.length,label:'组 '+g,level,parent:level?g*3+level-1:null,children:level<2?[g*3+level+1]:[],nodes:level===2?indices:[],x,y:0,bounds:[x-500,-200,x+500,200],node_count:indices.length,edge_count:indices.length,status_counts:{UNKNOWN:indices.length}});}const edges=Array.from({length:n-1},(_,i)=>[0,i+1,0,i%3,i]);edges.push([0,0,0,0,edges.length]);return {schema:'rds-archive-display-v1',nodes,edges,clusters,roots:[0,3],semantics:['original_dependency'],edge_types:['and_premise','source_binding','historical_revision'],bounds:[-2500,-300,2500,300],source:{node_count:n,edge_count:edges.length}};}
check('crossing segment is indexed with both endpoints outside',()=>{const points=[{x:-1000,y:0},{x:1000,y:0},{x:0,y:500}],edges=[{a:0,b:1},{a:0,b:2}],spatial=new Core.Spatial(points,edges,[-1000,-500,1000,500]),q=spatial.query([-10,-10,10,10]);assert.deepEqual(q.nodes,[]);assert.deepEqual(q.edges,[0]);assert.ok(q.counters.cells<20);});
check('zero-length, grid corner and moved crossing segment',()=>{const points=[{x:0,y:0},{x:160,y:160}],edges=[{a:0,b:0},{a:0,b:1}],s=new Core.Spatial(points,edges,[0,0,160,160]);assert.deepEqual(s.query([79,79,81,81]).edges,[1]);points[1].y=-160;s.node(1);s.edge(1);assert.equal(s.query([79,79,81,81]).edges.length,0);assert.deepEqual(s.query([79,-81,81,-79]).edges,[1]);});
check('full search keeps prototype identity, history and contradicted records',()=>{const data=fixture(),before=JSON.stringify(data),core=Core.create(data);assert.equal(core.byId.get('__proto__'),0);assert.equal(core.find('__proto__').entries[0].index,0);assert.equal(core.find('反驳').entries[0].index,2);assert.equal(core.find('历史').entries[0].index,2);assert.equal(JSON.stringify(data),before);});
check('all 80 incident relations survive pagination and self-loop',()=>{const core=Core.create(fixture());let seen=[];for(let p=0;p<4;p++){const m=core.neighbors(0,p);assert.equal(m.total,80);seen.push(...m.entries.map(e=>e.edge));}assert.equal(new Set(seen).size,80);assert.equal(core.neighbors(0,3).entries.length,8);assert.equal(core.neighbors(0,-1).page,0);assert.equal(core.neighbors(0,4).entries.length,0);});
check('coarse aggregate accounts for all original edges including internal',()=>{const core=Core.create(fixture());for(let level=0;level<3;level++){const s=core.levels[level];assert.equal(s.internal+s.edges.reduce((n,e)=>n+e.count,0),core.data.edges.length);}assert.equal(core.levels[3].edges.length,80);assert.equal(core.levels[0].points.length,2);});
check('display density bundling never silently truncates intersecting relations',()=>{const core=Core.create(fixture(800)),rect=[-30000,-500,30000,500],m=core.viewport(3,rect,5);assert.equal(m.counters.crossingEdges,800);assert.equal(m.counters.representedCrossingEdges,800);assert.equal(m.edges.reduce((n,e)=>n+e.count,0),800);assert.equal(m.counters.densityBundles,true);assert.equal(core.data.edges.length,800);});
check('viewport returns crossing endpoints but leaves full original lookup intact',()=>{const core=Core.create(fixture()),m=core.viewport(3,[-15,-15,15,15]);assert.ok(m.edges.length>0);assert.ok(m.points.some(p=>Math.abs(p.x)>15));assert.equal(core.neighbors(0).total,80);assert.equal(core.find('记录').total,80);});
check('fully connected visible tile keeps actual line budget and all multiplicity',()=>{const data=fixture(300);data.nodes.forEach((n,i)=>{n.x=(i%20)*10;n.y=Math.floor(i/20)*10;});data.edges=[];for(let a=0;a<300;a++)for(let b=a+1;b<300;b++)data.edges.push([a,b,0,0,data.edges.length]);data.bounds=[-1,-1,201,151];const m=Core.create(data).viewport(3,data.bounds,3500);assert.equal(m.counters.crossingEdges,44850);assert.ok(m.edges.length<=3500);assert.equal(m.edges.reduce((sum,e)=>sum+e.count,0),44850);});
check('unknown and snapshot membership never acquire dependency semantics',()=>{assert.equal(Core.family('UNKNOWN','UNKNOWN'),'other');assert.equal(Core.family('snapshot_contains','snapshot_member'),'source');assert.equal(Core.family('original_dependency','and_premise'),'dependency');assert.equal(Core.family('historical_revision','record'),'history');});
check('human status preserves import and evidence boundaries without scientific success',()=>{const ui=require('../scripts/hypergraph_archive/explorer.js');assert.equal(ui.status('SUPPORTED'),'声明支持');assert.equal(ui.status('CONTRADICTED'),'声明反驳');assert.equal(ui.status('COPIED_VERIFIED'),'副本已核验');assert.match(ui.status('VERIFIED_WITH_SOURCE_BOUNDARIES'),/边界/);assert.match(ui.status('SOURCE_HASH_DIFFERS'),/变化/);assert.match(ui.status('TENSOR_OR_TRANSPORT_ARCHIVE_NOT_IMPORTED'),/未导入/);assert.match(ui.status('EXCEEDS_8MIB'),/范围/);assert.match(ui.status('REVIEW_REQUIRED'),/待/);assert.match(ui.status('UNREVIEWED'),/未/);assert.equal(ui.status('INDEX_ONLY'),'仅索引');assert.equal(ui.status('unrecognized'),'未判定');});
check('dense source labels stay bounded, full names and identities remain intact',()=>{const ui=require('../scripts/hypergraph_archive/explorer.js'),points=Array.from({length:576},(_,i)=>({id:'source:'+i,label:'完整来源名称与用途 '.repeat(8)+i,type:'cluster',count:i+1,primary:i===0,degree:i})),before=JSON.stringify(points);const allowed=ui.labelIds(points,1);assert.equal(allowed.size,22);assert.ok(allowed.has('source:0'));assert.equal(ui.labelIds(points.slice(0,15),0).size,15);assert.equal(Array.from(ui.shortLabel(points[0].label)).length,28);assert.equal(ui.shortLabel('短名'),'短名');for(const p of points){assert.ok(ui.screenRadius(p,0)>=12&&ui.screenRadius(p,0)<=22);assert.ok(ui.screenRadius(p,1)>=6&&ui.screenRadius(p,1)<=9);assert.ok(ui.screenRadius(p,2)>=4&&ui.screenRadius(p,2)<=7);}assert.equal(JSON.stringify(points),before);});
check('offscreen heavy clusters do not consume local label allowance',()=>{const ui=require('../scripts/hypergraph_archive/explorer.js'),points=[...Array.from({length:22},(_,i)=>({id:'outside:'+i,type:'cluster',primary:true,count:1000,x:200,y:0})),...Array.from({length:3},(_,i)=>({id:'inside:'+i,type:'cluster',primary:false,count:1,x:0,y:0}))];assert.deepEqual([...ui.labelIds(points,1,[-10,-10,10,10])].sort(),['inside:0','inside:1','inside:2']);assert.equal(ui.labelIds(points,1).size,22);});
async function workerChecks(){
  const fs=require('node:fs'),vm=require('node:vm'),zlib=require('node:zlib'),path=require('node:path');
  const source=fs.readFileSync(path.join(__dirname,'../scripts/rds_hypergraph_view.py'),'utf8'),d3=source.split("D3_BUNDLE = r'''")[1].split("'''")[0];
  const tasks=new Map(),messages=[];let taskId=0,clock=0;
  const context=vm.createContext({console,Blob,Response,DecompressionStream,atob,Uint8Array,Uint32Array,Float32Array,ArrayBuffer,performance:{now:()=>clock},setTimeout:(fn)=>{const id=++taskId;tasks.set(id,fn);return id;},clearTimeout:id=>tasks.delete(id),setInterval:()=>++taskId,clearInterval(){},self:{postMessage:m=>messages.push(m)}});
  vm.runInContext(d3,context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../scripts/hypergraph_archive/worker.js'),'utf8'),context);
  const data=fixture(300);data.edges=[];for(let a=0;a<300;a++)for(let b=a+1;b<300;b++)data.edges.push([a,b,0,0,data.edges.length]);data.source.edge_count=data.edges.length;const before=JSON.stringify(data),compressed=zlib.gzipSync(before).toString('base64');
  await context.self.onmessage({data:{type:'init',compressed}});assert.ok(messages.some(m=>m.type==='ready'));
  const grid=fixture(300);grid.nodes.forEach((n,i)=>{n.x=(i%20)*10;n.y=Math.floor(i/20)*10;});grid.edges=data.edges;grid.bounds=[-1,-1,201,151];await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(grid)).toString('base64')}});await context.self.onmessage({data:{type:'viewport',level:3,rect:grid.bounds,edgeBudget:1000,request:43}});const budgeted=messages.find(m=>m.request===43);assert.ok(budgeted.counters.renderedEdges<=1000);assert.equal(budgeted.edges.reduce((n,e)=>n+e.count,0),44850);cases++;console.log('PASS worker request drawing budget preserves every visible relation multiplicity');
  await context.self.onmessage({data:{type:'init',compressed}});
  await context.self.onmessage({data:{type:'drag',id:'n0',x:data.nodes[0].x+120,y:data.nodes[0].y}});
  await context.self.onmessage({data:{type:'viewport',level:3,rect:data.bounds,request:42}});assert.equal(messages.some(m=>m.request===42),false);
  let iterations=0;while(tasks.size&&iterations++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}
  assert.ok(iterations<1000,'physics and exact index repair cool to a stop');const physics=messages.filter(m=>m.type==='physics');assert.ok(physics.length>2);assert.ok(physics.every(m=>m.nodes<=512&&m.springs<=1024));assert.ok(physics.at(-1).settled);assert.ok(messages.some(m=>m.type==='positions-updated'));assert.ok(messages.filter(m=>m.type==='index-progress').every(m=>m.visited<=2000));assert.equal(messages.find(m=>m.request===42).counters.totalEdges,44850);const final=new Float32Array(physics.at(-1).buffer);assert.ok(Math.abs(final[2]-data.nodes[1].x)>1,'neighbor follows the dragged point');assert.equal(JSON.stringify(data),before);cases++;console.log('PASS production D3 drag moves neighbors with bounded springs and exact deferred viewport');
  await context.self.onmessage({data:{type:'drag',id:'n0',x:null,y:null}});let loops=0;while(tasks.size&&loops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(loops<1000);assert.ok(messages.filter(m=>m.type==='physics').at(-1).settled);cases++;console.log('PASS production drag release cools and stops');
  await context.self.onmessage({data:{type:'drag',id:'n0',x:1,y:1}});await context.self.onmessage({data:{type:'pause'}});let pauseLoops=0;while(tasks.size&&pauseLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(pauseLoops<1000);assert.equal(tasks.size,0);cases++;console.log('PASS production pause stops force and completes exact index repair');
  const small=fixture(4);small.nodes.forEach((n,i)=>{n.x=[0,20,1000,1020][i];n.y=i<2?0:1000;});small.edges=[[0,1,0,0,0],[2,3,0,0,1]];small.bounds=[-1,-1,1050,1050];small.source.edge_count=2;
  await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(small)).toString('base64')}});const from=messages.length;await context.self.onmessage({data:{type:'drag',id:'n0',x:500,y:0}});let first=0;while(!messages.slice(from).some(m=>m.type==='physics')&&tasks.size&&first++<20){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}await context.self.onmessage({data:{type:'drag',id:'n2',x:1200,y:1000}});let switchLoops=0;while(tasks.size&&switchLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}await context.self.onmessage({data:{type:'viewport',level:3,rect:[490,-10,510,10],request:71}});assert.equal(messages.find(m=>m.request===71).counters.crossingEdges,1);cases++;console.log('PASS interrupted neighborhood drag retains earlier dirty crossing edge');
  for(const ci of [0,1,2]){await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(small)).toString('base64')}});await context.self.onmessage({data:{type:'drag',id:'c'+ci,x:700,y:500}});await context.self.onmessage({data:{type:'pause'}});await context.self.onmessage({data:{type:'locate',index:0,request:80+ci}});assert.equal(messages.find(m=>m.request===80+ci).x,1300);assert.equal(messages.find(m=>m.request===80+ci).y,500);}cases++;console.log('PASS each cluster level commits descendant coordinates before pause');
  const star=fixture(2504);star.nodes.forEach((n,i)=>{n.x=i===0?0:i<2502?-100:1000+(i-2502)*20;n.y=i===0?0:i<2502?-100+i*.08:1000;});star.edges=[];for(let i=1;i<2502;i++)star.edges.push([0,i,0,0,star.edges.length]);star.edges.push([2502,2503,0,0,star.edges.length]);star.bounds=[-150,-150,1300,1300];star.source.edge_count=star.edges.length;
  await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(star)).toString('base64')}});const largeStart=messages.length;await context.self.onmessage({data:{type:'drag',id:'n0',x:500,y:0}});let largeFirst=0;while(!messages.slice(largeStart).some(m=>m.type==='physics')&&tasks.size&&largeFirst++<20){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}await context.self.onmessage({data:{type:'drag',id:'n2502',x:5000,y:1000}});let largeLoops=0;while(tasks.size&&largeLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(largeLoops<1000);const progress=messages.slice(largeStart).filter(m=>m.type==='index-progress');assert.ok(progress.length>=2);assert.ok(progress[0].remaining>0);assert.equal(progress.at(-1).remaining,0);await context.self.onmessage({data:{type:'viewport',level:3,rect:[490,-10,510,10],request:91}});assert.equal(messages.find(m=>m.request===91).counters.crossingEdges,2501);const refreshed=messages.slice(largeStart).filter(m=>m.type==='bounds-updated').at(-1).bounds;assert.ok(refreshed[2]>=5000,'current moved node stays inside refreshed fit bounds');assert.ok(refreshed[0]<=-1100,'cluster bounds also remain represented');cases++;console.log('PASS dirty union over 2000 survives switch to one edge and refreshes full bounds');
  async function drainToStep(start,step){let loops=0;while((messages.slice(start).filter(m=>m.type==='physics').at(-1)?.steps||0)<step&&tasks.size&&loops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(loops<1000);return messages.slice(start).filter(m=>m.type==='physics').at(-1);}
  const long=fixture(4);long.nodes.forEach((n,i)=>{n.x=i<2?i*18000:50000+(i-2)*18000;n.y=0;});long.edges=[[0,1,0,0,0],[2,3,0,0,1],[0,2,0,0,2]];long.bounds=[-50,-50,68050,50];long.source.edge_count=3;const longBefore=JSON.stringify(long);await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(longBefore).toString('base64')}});const longStart=messages.length;await context.self.onmessage({data:{type:'drag',id:'n0',x:120,y:120}});await drainToStep(longStart,1);await context.self.onmessage({data:{type:'drag',id:'n0',x:null,y:null}});const longAfter=await drainToStep(longStart,27),longCoords=new Float32Array(longAfter.buffer);assert.ok(Math.hypot(longCoords[0]-120,longCoords[1]-120)<=120,'released point stays in its dragged neighborhood despite long archive links');assert.ok(Math.abs(longCoords[2]-18000)>1,'long-link neighbor still responds');let longLoops=0;while(tasks.size&&longLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(longLoops<1000);assert.ok(messages.slice(longStart).filter(m=>m.type==='physics').at(-1).settled);assert.equal(JSON.stringify(long),longBefore);cases++;console.log('PASS released long-span point stays nearby while neighbors respond and force cools');
  const responses=[];for(const familyType of ['and_premise','source_binding','historical_revision']){const pair=fixture(2);pair.nodes[0].x=0;pair.nodes[1].x=20;pair.nodes.forEach(n=>n.y=0);pair.edges=[[0,1,0,0,0]];pair.edge_types=[familyType];pair.bounds=[-500,-500,500,500];pair.source.edge_count=1;await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(pair)).toString('base64')}});const familyStart=messages.length;await context.self.onmessage({data:{type:'drag',id:'n0',x:120,y:0}});await drainToStep(familyStart,1);await context.self.onmessage({data:{type:'drag',id:'n0',x:null,y:null}});const m=await drainToStep(familyStart,27);responses.push(new Float32Array(m.buffer)[2]);await context.self.onmessage({data:{type:'pause'}});let cleanup=0;while(tasks.size&&cleanup++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}}assert.ok(responses.every(Number.isFinite));assert.ok(Math.abs(responses[0]-20)>1,'short dependency still moves its neighbor: '+responses.join(','));assert.ok(Math.abs(responses[0]-responses[1])>1,'dependency and source response differ: '+responses.join(','));assert.ok(Math.abs(responses[1]-responses[2])>1,'source and history response differ: '+responses.join(','));cases++;console.log('PASS short-link neighbors still move with distinct dependency/source/history forces');
  const coarse=fixture(4);coarse.nodes.forEach((n,i)=>{n.x=i<2?i*20:18000+(i-2)*20;n.y=0;});coarse.clusters.forEach((c,i)=>{c.x=i<3?0:18000;c.y=0;c.bounds=[c.x-100,-100,c.x+100,100];});coarse.edges=[[0,2,0,0,0]];coarse.bounds=[-100,-100,18100,100];coarse.source.edge_count=1;await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(coarse)).toString('base64')}});const coarseStart=messages.length;await context.self.onmessage({data:{type:'drag',id:'c0',x:120,y:120}});await drainToStep(coarseStart,1);await context.self.onmessage({data:{type:'drag',id:'c0',x:null,y:null}});const coarseAfter=await drainToStep(coarseStart,27),coarseCoords=new Float32Array(coarseAfter.buffer);assert.ok(Math.hypot(coarseCoords[0]-120,coarseCoords[1]-120)<=120);assert.ok(Math.abs(coarseCoords[2]-18000)>1);let coarseLoops=0;while(tasks.size&&coarseLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(coarseLoops<1000);await context.self.onmessage({data:{type:'locate',index:0,request:101}});const movedChild=messages.find(m=>m.request===101);assert.ok(Math.hypot(movedChild.x-120,movedChild.y-120)<=120,'release anchor does not replace the origin used to commit child shifts');assert.ok(messages.slice(coarseStart).filter(m=>m.type==='physics').at(-1).settled);cases++;console.log('PASS long-span aggregate release preserves shape and commits moved children');
}
workerChecks().then(()=>console.log(JSON.stringify({pass:cases,fail:0,skip:0}))).catch(error=>{console.error(error);process.exitCode=1;});
