'use strict';
const assert=require('node:assert/strict');
const Core=require('../scripts/hypergraph_archive/worker.js');
let cases=0;function check(name,fn){fn();cases++;console.log('PASS '+name);}
function fixture(n=80){const nodes=Array.from({length:n},(_,i)=>({id:i===0?'__proto__':'record:'+i,label:'记录 '+i,summary:i===2?'历史用途':'',type:i===1?'hyperedge':'claim',status:i===2?'CONTRADICTED':i===3?'SUPPORTED':'UNKNOWN',group:i<n/2?'A':'B',source_id:'source',primary:i===0,x:(i-n/2)*56,y:i%2?100:-100,parent:i<n/2?2:5}));const clusters=[];for(let g=0;g<2;g++){const indices=nodes.map((_,i)=>i).filter(i=>g===0?i<n/2:i>=n/2),x=g===0?-600:600;for(let level=0;level<3;level++)clusters.push({id:'c'+clusters.length,label:'组 '+g,level,parent:level?g*3+level-1:null,children:level<2?[g*3+level+1]:[],nodes:level===2?indices:[],x,y:0,bounds:[x-500,-200,x+500,200],node_count:indices.length,edge_count:indices.length,status_counts:{UNKNOWN:indices.length}});}const edges=Array.from({length:n-1},(_,i)=>[0,i+1,0,i%3,i]);edges.push([0,0,0,0,edges.length]);return {schema:'rds-archive-display-v1',nodes,edges,clusters,roots:[0,3],semantics:['original_dependency'],edge_types:['and_premise','source_binding','historical_revision'],bounds:[-2500,-300,2500,300],source:{node_count:n,edge_count:edges.length}};}
check('coarse create keeps complete raw identities and CSR without raw spatial work',()=>{const data=fixture(160),before=JSON.stringify(data),progress=[],core=Core.create(data,p=>progress.push(p));assert.equal(core.levels[3].spatial,null);assert.equal(core.indexStats.rawSpatialBuilds,0);assert.equal(core.indexStats.rawSpatialEdgeVisits,0);assert.equal(core.levels[3].edges.length,160);assert.equal(core.find('record:159').entries[0].index,159);assert.equal(core.neighbors(0,0,100).total,160);core.viewport(0,data.bounds);assert.equal(core.levels[3].spatial,null);assert.equal(progress.at(-1).spatialReady,false);const actual=core.viewport(3,[-15,-15,15,15]),eager=new Core.Spatial(core.levels[3].points,core.levels[3].edges,data.bounds).query([-15,-15,15,15]);assert.equal(core.indexStats.rawSpatialBuilds,1);assert.equal(core.indexStats.rawSpatialEdgeVisits,160);assert.equal(actual.counters.crossingEdges,eager.edges.length);assert.equal(actual.counters.visibleNodes,eager.nodes.length);core.viewport(3,data.bounds);assert.equal(core.indexStats.rawSpatialBuilds,1);assert.equal(JSON.stringify(data),before);});
check('crossing segment is indexed with both endpoints outside',()=>{const points=[{x:-1000,y:0},{x:1000,y:0},{x:0,y:500}],edges=[{a:0,b:1},{a:0,b:2}],spatial=new Core.Spatial(points,edges,[-1000,-500,1000,500]),q=spatial.query([-10,-10,10,10]);assert.deepEqual(q.nodes,[]);assert.deepEqual(q.edges,[0]);assert.ok(q.counters.cells<20);});
check('remote empty viewport and world-sized query examine only finite occupied work',()=>{const points=[{x:-1000,y:0},{x:1000,y:0},{x:0,y:500}],edges=[{a:0,b:1},{a:0,b:2}],s=new Core.Spatial(points,edges,[-1000,-500,1000,500]);const far=s.query([1e15,1e15,2e15,2e15]);assert.deepEqual(far.nodes,[]);assert.deepEqual(far.edges,[]);assert.equal(far.counters.examinedCells,0);const all=s.query([-1e15,-1e15,1e15,1e15]);assert.deepEqual(all.edges.sort((a,b)=>a-b),[0,1]);assert.equal(all.nodes.length,3);assert.ok(all.counters.examinedCells<=all.counters.occupiedCells);assert.deepEqual(s.query([-10,-10,10,10]).edges,[0]);points.push({x:1e20,y:1e20});s.node(3);assert.deepEqual(s.query([1e20,1e20,1e20,1e20]).nodes,[3]);});
check('zero-length, grid corner and moved crossing segment',()=>{const points=[{x:0,y:0},{x:160,y:160}],edges=[{a:0,b:0},{a:0,b:1}],s=new Core.Spatial(points,edges,[0,0,160,160]);assert.deepEqual(s.query([79,79,81,81]).edges,[1]);points[1].y=-160;s.node(1);s.edge(1);assert.equal(s.query([79,79,81,81]).edges.length,0);assert.deepEqual(s.query([79,-81,81,-79]).edges,[1]);});
check('raw spatial queries match complete direct geometry across empty and crossing viewports',()=>{const data=fixture(80),core=Core.create(data),stage=core.levels[3];for(let j=-8;j<=8;j++){const rect=[j*320-20,-110,j*320+20,110],q=core.ensureSpatial(3).query(rect);assert.deepEqual(q.nodes.sort((a,b)=>a-b),stage.points.map((p,i)=>i).filter(i=>stage.points[i].x>=rect[0]&&stage.points[i].x<=rect[2]&&stage.points[i].y>=rect[1]&&stage.points[i].y<=rect[3]));assert.deepEqual(q.edges.sort((a,b)=>a-b),stage.edges.map((e,i)=>i).filter(i=>Core.intersects(stage.points[stage.edges[i].a],stage.points[stage.edges[i].b],rect)));}assert.equal(core.indexStats.rawSpatialBuilds,1);assert.equal(core.levels[3].edges.length,80);});
check('overview uses bounded actual records with original coordinates status and no invented edges',()=>{const data=fixture(200),before=JSON.stringify(data),core=Core.create(data),m=core.viewport(0,[-1e6,-1e6,1e6,1e6]),records=m.points.filter(p=>p.representative);assert.equal(records.length,64);assert.equal(m.counters.representatives,64);assert.equal(m.counters.representativeCandidates,64);assert.equal(m.counters.densityStars,0);assert.equal(new Set(records.map(p=>p.index)).size,64);assert.ok(records.some(p=>p.index===0));assert.ok(records.some(p=>p.index===1));for(const p of records){const original=data.nodes[p.index];assert.equal(p.id,'n'+p.index);assert.equal(p.raw,true);assert.equal(p.x,original.x);assert.equal(p.y,original.y);assert.equal(p.label,original.label);assert.equal(p.type,original.type);assert.equal(p.status,original.status);assert.ok(!p.zoomOnly);}assert.equal(m.edges.reduce((sum,e)=>sum+e.count,0)+m.counters.internalEdges,data.edges.length);assert.equal(core.levels[3].spatial,null);assert.equal(core.neighbors(0,0,100).total,200);assert.equal(JSON.stringify(data),before);});
check('full search keeps prototype identity, history and contradicted records',()=>{const data=fixture(),before=JSON.stringify(data),core=Core.create(data);assert.equal(core.byId.get('__proto__'),0);assert.equal(core.find('__proto__').entries[0].index,0);assert.equal(core.find('反驳').entries[0].index,2);assert.equal(core.find('历史').entries[0].index,2);assert.equal(JSON.stringify(data),before);});
check('all 80 incident relations survive pagination and self-loop',()=>{const core=Core.create(fixture());let seen=[];for(let p=0;p<4;p++){const m=core.neighbors(0,p);assert.equal(m.total,80);seen.push(...m.entries.map(e=>e.edge));}assert.equal(new Set(seen).size,80);assert.equal(core.neighbors(0,3).entries.length,8);assert.equal(core.neighbors(0,-1).page,0);assert.equal(core.neighbors(0,4).entries.length,0);});
check('coarse aggregate accounts for all original edges including internal',()=>{const core=Core.create(fixture());for(let level=0;level<3;level++){const s=core.levels[level];assert.equal(s.internal+s.edges.reduce((n,e)=>n+e.count,0),core.data.edges.length);}assert.equal(core.levels[3].edges.length,80);assert.equal(core.levels[0].points.length,2);});
check('display density bundling never silently truncates intersecting relations',()=>{const core=Core.create(fixture(800)),rect=[-30000,-500,30000,500],m=core.viewport(3,rect,5);assert.equal(m.counters.crossingEdges,800);assert.equal(m.counters.representedCrossingEdges,800);assert.equal(m.edges.reduce((n,e)=>n+e.count,0),800);assert.equal(m.counters.densityBundles,true);assert.equal(core.data.edges.length,800);});
check('viewport uses separate clipped connection anchors and leaves full original lookup intact',()=>{const core=Core.create(fixture()),m=core.viewport(3,[-15,-15,15,15]);assert.ok(m.edges.length>0);assert.ok(m.anchors.length>0);assert.ok(m.points.every(p=>Math.abs(p.x)<=15&&Math.abs(p.y)<=15));assert.ok(m.anchors.every(p=>p.anchor&&Math.abs(p.x)<=15&&Math.abs(p.y)<=15));assert.equal(core.neighbors(0).total,80);assert.equal(core.find('记录').total,80);});
check('offscreen endpoints never collapse affordable visible records into a glyph grid',()=>{
  const data=fixture(42);data.nodes[0].x=-2;data.nodes[0].y=1;data.nodes[1].x=3;data.nodes[1].y=-1;data.nodes[0].color='#123456';data.nodes[0].shape='square';data.nodes[0].goal_weights={goal:.6};data.edges=[];
  for(let i=0;i<20;i++){const a=2+i*2;Object.assign(data.nodes[a],{x:-100-i,y:-9+i*.9});Object.assign(data.nodes[a+1],{x:100+i,y:-9+i*.9});data.edges.push([a,a+1,0,0,i]);}
  data.edges.push([0,1,0,0,20],[0,2,0,0,21]);data.bounds=[-130,-20,130,20];data.source.edge_count=data.edges.length;
  const before=JSON.stringify(data),core=Core.create(data),m=core.viewport(3,[-10,-10,10,10],100,16);
  assert.equal(m.counters.nodeAggregation,false);assert.deepEqual(m.points.map(p=>p.id),['n0','n1']);assert.ok(m.points.every(p=>p.raw&&p.count===1));
  for(const p of m.points)for(const key of ['x','y','status','type','color','shape','goal_weights'])assert.deepEqual(p[key],data.nodes[p.index][key]);
  assert.ok(m.edges.some(e=>e.source==='n0'&&e.target==='n1'&&!e.summary),'nearby original relation stays exact');assert.equal(m.edges.reduce((n,e)=>n+e.count,0),22);
  assert.ok(m.points.length<=16&&m.anchors.length<=256&&m.edges.length<=100);assert.ok(m.anchors.every(p=>p.anchor&&!p.raw&&!p.zoomOnly&&!('index' in p)));
  const anchors=new Map(m.anchors.map(p=>[p.id,p]));for(const e of m.edges.filter(e=>e.summary)){const a=data.nodes[e.a],b=data.nodes[e.b];for(const id of [e.source,e.target]){const p=anchors.get(id);assert.ok(Math.abs((p.x-a.x)*(b.y-a.y)-(p.y-a.y)*(b.x-a.x))<1e-7,'summary is clipped original geometry, not a grid-centre segment');}}
  assert.equal(core.find('记录').total,42);assert.equal(core.neighbors(0).total,2);assert.equal(JSON.stringify(data),before);
});
check('full visible glyph budget leaves separate bounded crossing geometry without aggregation',()=>{
  const data=fixture(56);data.nodes.forEach((p,i)=>{p.x=i<16?i/2-4:i%2?-100:100;p.y=i<16?0:((i-16)%20)/2-5;});data.edges=Array.from({length:20},(_,i)=>[16+i*2,17+i*2,0,0,i]);data.bounds=[-110,-10,110,10];data.source.edge_count=20;
  const m=Core.create(data).viewport(3,[-10,-10,10,10],8,16);assert.equal(m.points.length,16);assert.equal(m.counters.nodeAggregation,false);assert.ok(m.points.every(p=>p.raw));assert.ok(m.anchors.length<=16);assert.ok(m.edges.length<=8);assert.equal(m.edges.reduce((sum,e)=>sum+e.count,0),20);
});
check('fully connected visible tile keeps actual line budget and all multiplicity',()=>{const data=fixture(300);data.nodes.forEach((n,i)=>{n.x=(i%20)*10;n.y=Math.floor(i/20)*10;});data.edges=[];for(let a=0;a<300;a++)for(let b=a+1;b<300;b++)data.edges.push([a,b,0,0,data.edges.length]);data.bounds=[-1,-1,201,151];const m=Core.create(data).viewport(3,data.bounds,3500);assert.equal(m.counters.crossingEdges,44850);assert.ok(m.edges.length<=3500);assert.equal(m.edges.reduce((sum,e)=>sum+e.count,0),44850);});
check('raw view node budget aggregates all visible and isolated records without losing crossings or lookup',()=>{const data=fixture(5000);data.nodes.forEach((n,i)=>{n.x=i%100;n.y=Math.floor(i/100);});data.nodes[0].x=-1000;data.nodes[1].x=1000;data.nodes[0].y=data.nodes[1].y=20;data.edges=[[0,1,0,0,0]];data.bounds=[-1000,-100,1000,100];data.source.edge_count=1;const before=JSON.stringify(data),core=Core.create(data),m=core.viewport(3,[-1,-1,101,51],3500,100);assert.ok(m.points.length<=100);assert.equal(m.counters.representedVisibleNodes,4998);assert.equal(m.counters.aggregatedNodes,4998);assert.equal(m.counters.nodeAggregation,true);assert.equal(m.points.reduce((n,p)=>n+p.count,0),4998);assert.ok(m.points.every(p=>p.zoomOnly&&p.raw===false&&p.count>0));assert.equal(m.counters.crossingEdges,1);assert.equal(m.edges.reduce((n,e)=>n+e.count,0),1);assert.equal(core.find('record:4999').entries[0].index,4999);assert.equal(core.neighbors(0).total,1);const close=core.viewport(3,[98.9,48.9,99.1,49.1]);assert.equal(close.counters.nodeAggregation,false);assert.ok(close.points.some(p=>p.id==='n4999'));assert.equal(JSON.stringify(data),before);});
check('node and line budgets jointly preserve complete visible graph multiplicity',()=>{const data=fixture(180);data.nodes.forEach((n,i)=>{n.x=i%18;n.y=Math.floor(i/18);});data.edges=[];for(let a=0;a<180;a++)for(let b=a+1;b<180;b++)data.edges.push([a,b,0,a%3,data.edges.length]);data.bounds=[-1,-1,19,11];const core=Core.create(data),m=core.viewport(3,data.bounds,100,64);assert.ok(m.points.length<=64);assert.ok(m.edges.length<=100);assert.equal(m.points.reduce((n,p)=>n+p.count,0),180);assert.equal(m.edges.reduce((n,e)=>n+e.count,0),16110);assert.equal(m.counters.totalEdges,16110);assert.equal(m.counters.representedVisibleNodes,180);data.nodes.forEach(n=>{n.x=0;n.y=0;});const coincident=Core.create(data).viewport(3,[0,0,0,0],100,16);assert.equal(coincident.points.reduce((n,p)=>n+p.count,0),180);assert.ok(coincident.points.every(p=>p.x===0&&p.y===0));assert.equal(coincident.edges.reduce((n,e)=>n+e.count,0),16110);});
check('connection summary points share the final drawing budget at both boundaries',()=>{
  for(const [n,lines,budget] of [[16,101,100],[3500,3501,3500]]){
    const data=fixture(n);data.edges=Array.from({length:lines},(_,i)=>[0,n-1,0,0,i]);data.source.edge_count=lines;data.bounds=[-n*56,-101,n*56,101];
    const before=JSON.stringify(data),core=Core.create(data),m=core.viewport(3,data.bounds,budget,n);
    assert.ok(m.points.length<=n,'individual records plus connection summaries fit the drawing budget');
    assert.equal(m.counters.representedVisibleNodes,n);assert.equal(m.points.reduce((sum,p)=>sum+p.count,0),n);
    assert.equal(m.edges.reduce((sum,e)=>sum+e.count,0),lines);assert.equal(core.find('记录').total,n);assert.equal(core.neighbors(0).total,lines);
    assert.equal(JSON.stringify(data),before);
  }
});
check('many roots retain every group while sharing one global representative allowance',()=>{
  const data=fixture(3410);data.edges=[];data.clusters=[];data.roots=[];data.source.edge_count=0;
  for(let group=0;group<110;group++){
    const members=Array.from({length:31},(_,j)=>group*31+j);data.roots.push(group*3);
    for(const i of members){data.nodes[i].parent=group*3+2;data.nodes[i].x=group*10;data.nodes[i].y=i%31;}
    for(let level=0;level<3;level++)data.clusters.push({id:'c'+data.clusters.length,label:'组 '+group,level,parent:level?group*3+level-1:null,children:[],nodes:level===2?members:[],x:group*10,y:15,bounds:[group*10-1,-1,group*10+1,32],node_count:31,edge_count:0});
  }
  data.bounds=[-1,-1,1101,33];const before=JSON.stringify(data),core=Core.create(data),m=core.viewport(0,data.bounds,3500,3500);
  assert.equal(m.points.filter(p=>p.type==='cluster').length,110);assert.equal(m.points.length,3500);assert.equal(m.counters.representatives,3390);
  assert.equal(new Set(m.points.map(p=>p.id)).size,3500);assert.equal(core.find('记录').total,3410);assert.equal(JSON.stringify(data),before);
  const tiny=core.viewport(0,data.bounds,100,16);assert.ok(tiny.points.length<=16);assert.equal(tiny.points.reduce((sum,p)=>sum+p.count,0),110);assert.equal(tiny.counters.nodeAggregation,true);
});
check('unknown and snapshot membership never acquire dependency semantics',()=>{assert.equal(Core.family('UNKNOWN','UNKNOWN'),'other');assert.equal(Core.family('snapshot_contains','snapshot_member'),'source');assert.equal(Core.family('original_dependency','and_premise'),'dependency');assert.equal(Core.family('historical_revision','record'),'history');});
check('human status preserves import and evidence boundaries without scientific success',()=>{const ui=require('../scripts/hypergraph_archive/explorer.js');assert.equal(ui.status('SUPPORTED'),'声明支持');assert.equal(ui.status('CONTRADICTED'),'声明反驳');assert.equal(ui.status('COPIED_VERIFIED'),'副本已核验');assert.match(ui.status('VERIFIED_WITH_SOURCE_BOUNDARIES'),/边界/);assert.match(ui.status('SOURCE_HASH_DIFFERS'),/变化/);assert.match(ui.status('TENSOR_OR_TRANSPORT_ARCHIVE_NOT_IMPORTED'),/未导入/);assert.match(ui.status('EXCEEDS_8MIB'),/范围/);assert.match(ui.status('REVIEW_REQUIRED'),/待/);assert.match(ui.status('UNREVIEWED'),/未/);assert.equal(ui.status('INDEX_ONLY'),'仅索引');assert.equal(ui.status('unrecognized'),'未判定');});
check('generic archived nodes preserve typed identities for readable categories without filename inference',()=>{
  const ui=require('../scripts/hypergraph_archive/explorer.js'),data=fixture(4),types=['run','receipt','fact','output'];
  data.nodes.forEach((n,i)=>{n.type='original_node';n.id='db:owned:'+types[i]+':original';});const before=JSON.stringify(data),core=Core.create(data),m=core.viewport(3,data.bounds);
  for(let i=0;i<4;i++){const p=m.points.find(p=>p.index===i);assert.equal(p.record,data.nodes[i].id);assert.equal(ui.nodeStyle(p).kind,['执行','回执','事实','产物'][i]);}
  assert.equal(ui.nodeStyle({type:'original_node',id:'stdout.run.failed.bin'}).kind,'记录');assert.equal(ui.nodeStyle({type:'unknown'}).kind,'记录');
  assert.equal(JSON.stringify(data),before);
});
check('dense source labels stay bounded, full names and identities remain intact',()=>{const ui=require('../scripts/hypergraph_archive/explorer.js'),points=Array.from({length:576},(_,i)=>({id:'source:'+i,label:'完整来源名称与用途 '.repeat(8)+i,type:'cluster',count:i+1,primary:i===0,degree:i})),before=JSON.stringify(points);const allowed=ui.labelIds(points,1);assert.equal(allowed.size,22);assert.ok(allowed.has('source:0'));assert.equal(ui.labelIds(points.slice(0,15),0).size,15);assert.equal(Array.from(ui.shortLabel(points[0].label)).length,28);assert.equal(ui.shortLabel('短名'),'短名');for(const p of points){assert.ok(ui.screenRadius(p,0)>=7&&ui.screenRadius(p,0)<=14);assert.ok(ui.screenRadius(p,1)>=5&&ui.screenRadius(p,1)<=9);assert.ok(ui.screenRadius(p,2)>=4&&ui.screenRadius(p,2)<=7);}assert.equal(JSON.stringify(points),before);});
check('offscreen heavy clusters do not consume local label allowance',()=>{const ui=require('../scripts/hypergraph_archive/explorer.js'),points=[...Array.from({length:22},(_,i)=>({id:'outside:'+i,type:'cluster',primary:true,count:1000,x:200,y:0})),...Array.from({length:3},(_,i)=>({id:'inside:'+i,type:'cluster',primary:false,count:1,x:0,y:0}))];assert.deepEqual([...ui.labelIds(points,1,[-10,-10,10,10])].sort(),['inside:0','inside:1','inside:2']);assert.equal(ui.labelIds(points,1).size,22);});
check('search and detail retain native failure presentation without raw payloads',()=>{const data=fixture(4),n=data.nodes[1];Object.assign(n,{label:'native failed record',summary:'diagnostic purpose',status:'FAILED',status_text:'失败',display_kind:'回执',color:'#cc3344',shape:'ring',outline:{state:'failed',color:'#cc3344'},goal_weights:{native_goal:.5},private_raw:{mustNotProject:true}});const core=Core.create(data),search=core.find('native failed record').entries[0],detail=core.neighbors(0).entries.find(e=>e.index===1);for(const value of [search,detail]){for(const key of ['summary','status','status_text','display_kind','color','shape','outline','goal_weights'])assert.deepEqual(value[key],n[key]);assert.equal(Object.hasOwn(value,'private_raw'),false);}assert.equal(detail.node_type,n.type);assert.equal(core.neighbors(1).node.status_text,'失败');assert.equal(Object.hasOwn(core.neighbors(1).node,'private_raw'),false);});
check('active-relation orphan filtering applies to raw and semantic groups including internal edges',()=>{
  const data=fixture(6);data.edges=[[0,1,0,0,0],[3,4,1,1,1]];data.semantics=['original_dependency','snapshot_contains'];data.edge_types=['and_premise','membership'];data.source.edge_count=2;
  const core=Core.create(data),filters={membership:false,showOrphans:false},raw=core.viewport(3,[-10000,-10000,10000,10000],3500,3500,filters);
  assert.deepEqual(raw.points.map(p=>p.index),[0,1]);assert.equal(raw.edges.reduce((n,e)=>n+e.count,0),1);
  for(let level=0;level<3;level++){const groups=core.viewport(level,[-10000,-10000,10000,10000],3500,3500,filters).points.filter(p=>p.type==='cluster');assert.equal(groups.length,1);assert.equal(groups[0].index,level);assert.equal(groups[0].count,2,'internal connected members keep their group even without a coarse external edge');}
  assert.equal(core.neighbors(3).total,1,'display filtering preserves original membership lookup');assert.equal(core.find('记录').total,6);
});
check('cluster drill uses retained member bounds and an exact ancestry scope',()=>{
  const data=fixture(8);data.nodes[0].x=-20000;data.nodes[3].x=25000;const core=Core.create(data),focus=core.clusterView(0),ui=require('../scripts/hypergraph_archive/explorer.js');
  assert.equal(focus.total,4);assert.deepEqual(focus.memberBounds,[-20000,-100,25000,100]);
  const camera=ui.boundsCamera(focus.memberBounds,1000,700),rect=[camera.x-500/camera.scale,camera.y-350/camera.scale,camera.x+500/camera.scale,camera.y+350/camera.scale];
  const m=core.viewport(3,rect,3500,3500,{scope:0});assert.deepEqual(m.points.map(p=>p.index).sort((a,b)=>a-b),[0,1,2,3]);assert.equal(m.counters.displayFiltered,true);
  data.nodes[0].x=-40000;assert.equal(core.clusterView(0).memberBounds[0],-40000,'member bounds cannot rely on an obsolete group centre');
  const live=core.clusterView(0,{},i=>({x:data.nodes[i].x+500,y:data.nodes[i].y-300}));assert.deepEqual(live.memberBounds,[-39500,-400,25500,-200]);
  assert.throws(()=>core.clusterView(999),/out of range/);assert.equal(core.clusterView(0,{query:'no-match'}).total,0);
});
check('filtered coarse bundles count only retained raw relations',()=>{
  const data=fixture(8);data.nodes.forEach((n,i)=>n.label=i===0||i===4?'needle':'other');data.edges=[];for(let a=0;a<4;a++)for(let b=4;b<8;b++)data.edges.push([a,b,0,0,data.edges.length]);
  const core=Core.create(data);for(let level=0;level<4;level++){const m=core.viewport(level,[-1e6,-1e6,1e6,1e6],3500,3500,{query:'needle'});assert.equal(m.edges.reduce((n,e)=>n+e.count,0),1);assert.equal(m.counters.representedCrossingEdges,1);assert.equal(m.counters.totalEdges,16);}
  assert.equal(core.neighbors(0).total,4,'display bundle filtering does not change original adjacency');
});
check('drilling a group retains externally connected members and their boundary links',()=>{
  const data=fixture(8);data.edges=[[0,4,0,0,0],[1,5,0,0,1]];const core=Core.create(data),filters={showOrphans:false,membership:false};
  const parent=core.viewport(0,[-1e6,-1e6,1e6,1e6],3500,3500,filters).points.find(p=>p.id==='c0'),focus=core.clusterView(0,filters);assert.equal(focus.total,parent.count);assert.equal(focus.total,2);
  const m=core.viewport(3,[-1e6,-1e6,1e6,1e6],3500,3500,{...filters,scope:0});assert.deepEqual(m.points.map(p=>p.id),['n0','n1']);assert.equal(m.edges.reduce((n,e)=>n+e.count,0),2);assert.ok(m.anchors.length>0,'outside members stay geometry rather than scoped glyphs');
});
check('spatial cells retain world identities on pan and preserve singleton presentation',()=>{
  const data=fixture(4);Object.assign(data.nodes[0],{x:10,y:10});Object.assign(data.nodes[1],{x:15,y:15});Object.assign(data.nodes[2],{x:70,y:10,color:'#abcdef',shape:'hexagon'});Object.assign(data.nodes[3],{x:200,y:200});data.edges=[[0,2,0,0,0],[1,2,0,0,1]];data.bounds=[0,0,220,220];
  const core=Core.create(data),filters={cellSize:32},a=core.viewport(3,[0,0,100,100],3500,3500,filters),b=core.viewport(3,[-10,-10,110,110],3500,3500,filters);
  assert.deepEqual(a.points.map(p=>[p.id,p.x,p.y,p.count]),b.points.map(p=>[p.id,p.x,p.y,p.count]));assert.equal(a.points.reduce((n,p)=>n+p.count,0),3);assert.equal(a.edges.reduce((n,e)=>n+e.count,0),2);
  const singleton=a.points.find(p=>p.id==='n2');assert.equal(singleton.raw,true);assert.equal(singleton.color,'#abcdef');assert.equal(singleton.shape,'hexagon');
  const detail=core.viewport(3,[0,0,100,100],3500,3500,{cellSize:4});assert.deepEqual(detail.points.map(p=>p.id),['n0','n1','n2']);assert.equal(detail.counters.nodeAggregation,false);
  const ui=require('../scripts/hypergraph_archive/explorer.js'),size=ui.cellSize(1);assert.equal(ui.cellSize(.99,size),size);assert.equal(ui.cellSize(1.01,size),size);assert.equal(ui.cellSize(.5,size),size*2);assert.equal(ui.cellSize(2,size),size/2);
});
check('coincident density members remain paginated and a selected record keeps its actual glyph',()=>{
  const data=fixture(4000);data.nodes.forEach(n=>{n.x=0;n.y=0;});data.edges=[];data.bounds=[-1,-1,1,1];const core=Core.create(data),m=core.viewport(3,data.bounds,3500,3500,{cellSize:2});
  assert.equal(m.points.length,1);assert.equal(m.points[0].count,4000);const seen=[];for(let page=0;page<167;page++){const list=core.cellMembers(m.points[0].cell,{},page);assert.equal(list.total,4000);seen.push(...list.entries.map(n=>n.index));}assert.equal(new Set(seen).size,4000);
  const selected=core.viewport(3,data.bounds,3500,3500,{cellSize:2,selected:3999});assert.equal(selected.points.reduce((n,p)=>n+p.count,0),4000);assert.equal(selected.points.find(p=>p.id==='n3999').raw,true);assert.equal(selected.points.find(p=>p.type==='density').count,3999);assert.equal(core.cellMembers([2,0,0],{selected:3999}).total,3999);
});
async function workerChecks(){
  const fs=require('node:fs'),vm=require('node:vm'),zlib=require('node:zlib'),path=require('node:path');
  const source=fs.readFileSync(path.join(__dirname,'../scripts/rds_hypergraph_view.py'),'utf8'),d3=source.split("D3_BUNDLE = r'''")[1].split("'''")[0];
  const tasks=new Map(),messages=[];let taskId=0,clock=0;
  const context=vm.createContext({console,Blob,Response,DecompressionStream,atob,Uint8Array,Uint32Array,Float32Array,ArrayBuffer,performance:{now:()=>clock},setTimeout:(fn)=>{const id=++taskId;tasks.set(id,fn);return id;},clearTimeout:id=>tasks.delete(id),setInterval:()=>++taskId,clearInterval(){},self:{postMessage:m=>messages.push(m)}});
  vm.runInContext(d3,context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../scripts/hypergraph_archive/worker.js'),'utf8'),context);
  const data=fixture(300);data.edges=[];for(let a=0;a<300;a++)for(let b=a+1;b<300;b++)data.edges.push([a,b,0,0,data.edges.length]);data.source.edge_count=data.edges.length;const before=JSON.stringify(data),compressed=zlib.gzipSync(before).toString('base64');
  await context.self.onmessage({data:{type:'init',compressed}});assert.ok(messages.some(m=>m.type==='ready'));assert.equal(messages.filter(m=>m.type==='ready').at(-1).indexStats.rawSpatialBuilds,0);
  const grid=fixture(300);grid.nodes.forEach((n,i)=>{n.x=(i%20)*10;n.y=Math.floor(i/20)*10;});grid.edges=data.edges;grid.bounds=[-1,-1,201,151];await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(grid)).toString('base64')}});await context.self.onmessage({data:{type:'viewport',level:3,rect:grid.bounds,edgeBudget:1000,request:43}});const budgeted=messages.find(m=>m.request===43);assert.ok(budgeted.counters.renderedEdges<=1000);assert.equal(budgeted.edges.reduce((n,e)=>n+e.count,0),44850);cases++;console.log('PASS worker request drawing budget preserves every visible relation multiplicity');
  await context.self.onmessage({data:{type:'init',compressed}});
  await context.self.onmessage({data:{type:'drag',id:'n0',x:data.nodes[0].x+120,y:data.nodes[0].y}});
  await context.self.onmessage({data:{type:'viewport',level:3,rect:data.bounds,request:41}});assert.equal(messages.find(m=>m.request===41).counters.stableViewport,true);await context.self.onmessage({data:{type:'viewport',level:3,rect:data.bounds,request:42}});assert.equal(messages.find(m=>m.request===42).counters.totalEdges,44850);assert.equal(messages.find(m=>m.request===42).counters.stableViewport,true);
  let iterations=0;while(tasks.size&&iterations++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}
  assert.ok(iterations<1000,'physics and exact index repair cool to a stop');const physics=messages.filter(m=>m.type==='physics');assert.ok(physics.length>2);assert.ok(physics.every(m=>m.nodes<=512&&m.springs<=1024));assert.ok(physics.at(-1).settled);assert.ok(messages.some(m=>m.type==='positions-updated'));assert.ok(messages.filter(m=>m.type==='index-progress').every(m=>m.visited<=2000));assert.equal(messages.find(m=>m.request===42).counters.totalEdges,44850);const final=new Float32Array(physics.at(-1).buffer);assert.ok(Math.abs(final[2]-data.nodes[1].x)>1,'neighbor follows the dragged point');assert.equal(JSON.stringify(data),before);cases++;console.log('PASS production D3 drag moves neighbors with bounded springs and immediate stable viewport');
  await context.self.onmessage({data:{type:'drag',id:'n0',x:null,y:null}});let loops=0;while(tasks.size&&loops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(loops<1000);assert.ok(messages.filter(m=>m.type==='physics').at(-1).settled);cases++;console.log('PASS production drag release cools and stops');
  await context.self.onmessage({data:{type:'drag',id:'n0',x:1,y:1}});await context.self.onmessage({data:{type:'pause'}});let pauseLoops=0;while(tasks.size&&pauseLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(pauseLoops<1000);assert.equal(tasks.size,0);cases++;console.log('PASS production pause stops force and completes exact index repair');
  const small=fixture(4);small.nodes.forEach((n,i)=>{n.x=[0,20,1000,1020][i];n.y=i<2?0:1000;});small.edges=[[0,1,0,0,0],[2,3,0,0,1]];small.bounds=[-1,-1,1050,1050];small.source.edge_count=2;
  await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(small)).toString('base64')}});const from=messages.length;await context.self.onmessage({data:{type:'drag',id:'n0',x:500,y:0}});let first=0;while(!messages.slice(from).some(m=>m.type==='physics')&&tasks.size&&first++<20){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}await context.self.onmessage({data:{type:'drag',id:'n2',x:1200,y:1000}});let switchLoops=0;while(tasks.size&&switchLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}await context.self.onmessage({data:{type:'viewport',level:3,rect:[490,-10,510,10],request:71}});assert.equal(messages.find(m=>m.request===71).counters.crossingEdges,1);cases++;console.log('PASS interrupted neighborhood drag retains earlier dirty crossing edge');
  for(const ci of [0,1,2]){await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(small)).toString('base64')}});await context.self.onmessage({data:{type:'drag',id:'c'+ci,x:700,y:500}});await context.self.onmessage({data:{type:'pause'}});await context.self.onmessage({data:{type:'locate',index:0,request:80+ci}});assert.equal(messages.find(m=>m.request===80+ci).x,1300);assert.equal(messages.find(m=>m.request===80+ci).y,500);await context.self.onmessage({data:{type:'viewport',level:0,rect:[-1e4,-1e4,1e4,1e4],request:180+ci}});assert.equal(messages.find(m=>m.request===180+ci).counters.rawSpatialBuilds,0);await context.self.onmessage({data:{type:'viewport',level:3,rect:[1299,499,1301,501],request:280+ci}});const rawView=messages.find(m=>m.request===280+ci);assert.equal(rawView.counters.rawSpatialBuilds,1);assert.ok(rawView.points.some(p=>p.id==='n0'&&p.x===1300&&p.y===500));}cases++;console.log('PASS each cluster level commits children without raw index until the actual record viewport');
  await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(small)).toString('base64')}});await context.self.onmessage({data:{type:'viewport',level:3,rect:small.bounds,request:390}});await context.self.onmessage({data:{type:'drag',id:'c0',x:700,y:500}});await context.self.onmessage({data:{type:'pause'}});let repairLoops=0;while(tasks.size&&repairLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=8;fn();}assert.ok(repairLoops<1000);await context.self.onmessage({data:{type:'viewport',level:3,rect:[1299,499,1301,501],request:391}});const rebuilt=messages.find(m=>m.request===391);assert.equal(rebuilt.counters.rawSpatialBuilds,1);assert.ok(rebuilt.points.some(p=>p.id==='n0'&&p.x===1300&&p.y===500));cases++;console.log('PASS aggregate movement incrementally repairs an already requested raw index exactly');
  const star=fixture(2504);star.nodes.forEach((n,i)=>{n.x=i===0?0:i<2502?-100:1000+(i-2502)*20;n.y=i===0?0:i<2502?-100+i*.08:1000;});star.edges=[];for(let i=1;i<2502;i++)star.edges.push([0,i,0,0,star.edges.length]);star.edges.push([2502,2503,0,0,star.edges.length]);star.bounds=[-150,-150,1300,1300];star.source.edge_count=star.edges.length;
  await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(star)).toString('base64')}});await context.self.onmessage({data:{type:'viewport',level:3,rect:star.bounds,request:389}});const largeStart=messages.length;await context.self.onmessage({data:{type:'drag',id:'n0',x:500,y:0}});let largeFirst=0;while(!messages.slice(largeStart).some(m=>m.type==='physics')&&tasks.size&&largeFirst++<20){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}await context.self.onmessage({data:{type:'drag',id:'n2502',x:5000,y:1000}});let largeLoops=0;while(tasks.size&&largeLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(largeLoops<1000);const progress=messages.slice(largeStart).filter(m=>m.type==='index-progress');assert.ok(progress.length>=2);assert.ok(progress[0].remaining>0);assert.equal(progress.at(-1).remaining,0);await context.self.onmessage({data:{type:'viewport',level:3,rect:[490,-10,510,10],request:91}});assert.equal(messages.find(m=>m.request===91).counters.crossingEdges,2501);const refreshed=messages.slice(largeStart).filter(m=>m.type==='bounds-updated').at(-1).bounds;assert.ok(refreshed[2]>=5000,'current moved node stays inside refreshed fit bounds');assert.ok(refreshed[0]<=-1100,'cluster bounds also remain represented');cases++;console.log('PASS dirty union over 2000 survives switch to one edge and refreshes full bounds');
  async function drainToStep(start,step){let loops=0;while((messages.slice(start).filter(m=>m.type==='physics').at(-1)?.steps||0)<step&&tasks.size&&loops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(loops<1000);return messages.slice(start).filter(m=>m.type==='physics').at(-1);}
  const long=fixture(4);long.nodes.forEach((n,i)=>{n.x=i<2?i*18000:50000+(i-2)*18000;n.y=0;});long.edges=[[0,1,0,0,0],[2,3,0,0,1],[0,2,0,0,2]];long.bounds=[-50,-50,68050,50];long.source.edge_count=3;const longBefore=JSON.stringify(long);await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(longBefore).toString('base64')}});const longStart=messages.length;await context.self.onmessage({data:{type:'drag',id:'n0',x:120,y:120}});await drainToStep(longStart,1);await context.self.onmessage({data:{type:'drag',id:'n0',x:null,y:null}});const longAfter=await drainToStep(longStart,27),longCoords=new Float32Array(longAfter.buffer);assert.ok(Math.hypot(longCoords[0]-120,longCoords[1]-120)<=120,'released point stays in its dragged neighborhood despite long archive links');assert.ok(Math.abs(longCoords[2]-18000)>1,'long-link neighbor still responds');let longLoops=0;while(tasks.size&&longLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(longLoops<1000);assert.ok(messages.slice(longStart).filter(m=>m.type==='physics').at(-1).settled);assert.equal(JSON.stringify(long),longBefore);cases++;console.log('PASS released long-span point stays nearby while neighbors respond and force cools');
  const responses=[];for(const familyType of ['and_premise','source_binding','historical_revision']){const pair=fixture(2);pair.nodes[0].x=0;pair.nodes[1].x=20;pair.nodes.forEach(n=>n.y=0);pair.edges=[[0,1,0,0,0]];pair.edge_types=[familyType];pair.bounds=[-500,-500,500,500];pair.source.edge_count=1;await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(pair)).toString('base64')}});const familyStart=messages.length;await context.self.onmessage({data:{type:'drag',id:'n0',x:120,y:0}});await drainToStep(familyStart,1);await context.self.onmessage({data:{type:'drag',id:'n0',x:null,y:null}});const m=await drainToStep(familyStart,27);responses.push(new Float32Array(m.buffer)[2]);await context.self.onmessage({data:{type:'pause'}});let cleanup=0;while(tasks.size&&cleanup++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}}assert.ok(responses.every(Number.isFinite));assert.ok(Math.abs(responses[0]-20)>1,'short dependency still moves its neighbor: '+responses.join(','));assert.ok(Math.abs(responses[0]-responses[1])>1,'dependency and source response differ: '+responses.join(','));assert.ok(Math.abs(responses[1]-responses[2])>1,'source and history response differ: '+responses.join(','));cases++;console.log('PASS short-link neighbors still move with distinct dependency/source/history forces');
  const coarse=fixture(4);coarse.nodes.forEach((n,i)=>{n.x=i<2?i*20:18000+(i-2)*20;n.y=0;});coarse.clusters.forEach((c,i)=>{c.x=i<3?0:18000;c.y=0;c.bounds=[c.x-100,-100,c.x+100,100];});coarse.edges=[[0,2,0,0,0]];coarse.bounds=[-100,-100,18100,100];coarse.source.edge_count=1;await context.self.onmessage({data:{type:'init',compressed:zlib.gzipSync(JSON.stringify(coarse)).toString('base64')}});const coarseStart=messages.length;await context.self.onmessage({data:{type:'drag',id:'c0',x:120,y:120}});await drainToStep(coarseStart,1);await context.self.onmessage({data:{type:'drag',id:'c0',x:null,y:null}});const coarseAfter=await drainToStep(coarseStart,27),coarseCoords=new Float32Array(coarseAfter.buffer);assert.ok(Math.hypot(coarseCoords[0]-120,coarseCoords[1]-120)<=120);assert.ok(Math.abs(coarseCoords[2]-18000)>1);let coarseLoops=0;while(tasks.size&&coarseLoops++<1000){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}assert.ok(coarseLoops<1000);await context.self.onmessage({data:{type:'locate',index:0,request:101}});const movedChild=messages.find(m=>m.request===101);assert.ok(Math.hypot(movedChild.x-120,movedChild.y-120)<=120,'release anchor does not replace the origin used to commit child shifts');assert.ok(messages.slice(coarseStart).filter(m=>m.type==='physics').at(-1).settled);cases++;console.log('PASS long-span aggregate release preserves shape and commits moved children');
}
async function workerParityChecks(){
  const fs=require('node:fs'),vm=require('node:vm'),zlib=require('node:zlib'),path=require('node:path');
  const py=fs.readFileSync(path.join(__dirname,'../scripts/rds_hypergraph_view.py'),'utf8'),d3=py.split("D3_BUNDLE = r'''")[1].split("'''")[0];
  const tasks=new Map(),messages=[];let taskId=0,clock=0;
  const ctx=vm.createContext({console,Blob,Response,DecompressionStream,atob,Uint8Array,Uint32Array,Float32Array,ArrayBuffer,performance:{now:()=>clock},setTimeout:fn=>{const id=++taskId;tasks.set(id,fn);return id;},clearTimeout:id=>tasks.delete(id),setInterval:()=>++taskId,clearInterval(){},self:{postMessage:m=>messages.push(m)}});
  vm.runInContext(d3,ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../scripts/hypergraph_archive/worker.js'),'utf8'),ctx);
  const send=m=>ctx.self.onmessage({data:m});
  function one(){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}
  function drain(){let loops=0;while(tasks.size&&loops++<1500)one();assert.ok(loops<1500);}
  const base={damping:.55,flowStrength:0,groupStrength:0,edgeRepulsion:0,edgeClearance:35,centerStrength:0,repelStrength:0,linkStrength:1,linkDistance:80,membership:true,weightMode:'degree',goal:'',relations:{dependency:{mode:'attract',strength:1},source:{mode:'attract',strength:.35},history:{mode:'attract',strength:.15},other:{mode:'none',strength:1}}};
  async function init(data){await send({type:'init',compressed:zlib.gzipSync(JSON.stringify(data)).toString('base64')});}
  const pair=fixture(4);pair.nodes.forEach((n,i)=>{n.x=[-100,0,10,1000][i];n.y=0;n.source_id='same-source';n.type=i===1?'hyperedge':'claim';n.goal_weights={native_goal:i===2?1:0};});pair.edges=[[0,1,0,0,0],[0,2,0,0,1]];pair.bounds=[-200,-100,1100,100];pair.source.edge_count=2;
  async function response(delta={},dragX=100){await init(pair);await send({type:'configure',options:{...base,...delta}});const start=messages.length;await send({type:'drag',id:'n0',x:dragX,y:0});let loops=0;while((messages.slice(start).filter(m=>m.type==='physics').at(-1)?.steps||0)<12&&loops++<100)one();const packet=messages.slice(start).filter(m=>m.type==='physics').at(-1),positions=new Float32Array(packet.buffer),coords=pair.nodes.flatMap(n=>[n.x,n.y]);packet.ids.forEach((id,i)=>{const index=Number(id.slice(1));coords[index*2]=positions[i*2];coords[index*2+1]=positions[i*2+1];});await send({type:'pause'});drain();return coords;}
  const initial=await response();
  for(const [name,value] of [['damping',.1],['flowStrength',.08],['groupStrength',.15],['centerStrength',.3],['repelStrength',200],['linkStrength',0],['linkDistance',300]]){
    const changed=await response({[name]:value});assert.ok(changed.some((v,i)=>Math.abs(v-initial[i])>.01),'production force option changes response: '+name);cases++;console.log('PASS real worker '+name+' changes local response');
  }
  const clearanceBase=await response({edgeRepulsion:.3,edgeClearance:35},-100),noClearance=await response({edgeRepulsion:0,edgeClearance:35},-100),moreClearance=await response({edgeRepulsion:.3,edgeClearance:150},-100);
  assert.ok(clearanceBase.some((v,i)=>Math.abs(v-noClearance[i])>.01));assert.ok(clearanceBase.some((v,i)=>Math.abs(v-moreClearance[i])>.01));cases+=2;console.log('PASS real hyperedge repulsion and clearance change nonmember separation');
  const neutral=await response({relations:{dependency:{mode:'none',strength:1}}},-300),attract=await response({},-300),repel=await response({relations:{dependency:{mode:'repel',strength:1}}},-20);
  assert.ok(attract[2]<neutral[2]-1,'attraction follows the dragged endpoint');assert.ok(repel[2]>0,'repulsion moves a nearby neighbor away');const semantic=await response({relations:{'original_dependency|and_premise':{mode:'none',strength:1}}},-300);assert.deepEqual(semantic,neutral,'individual semantic/type overrides the family');const zero=await response({relations:{'original_dependency|and_premise':{mode:'attract',strength:0}}},-300);assert.deepEqual(zero,neutral,'zero relation strength disables its spring');cases++;console.log('PASS semantic/type and family attraction repulsion none and strength reach D3');
  await send({type:'configure',options:{relations:{'original_dependency|and_premise':{mode:'attract',strength:1}}}});
  const uniform=await response({repelStrength:100,linkStrength:0,weightMode:'uniform'}),degree=await response({repelStrength:100,linkStrength:0,weightMode:'degree'}),goal=await response({repelStrength:100,linkStrength:0,weightMode:'goal',goal:'native_goal'});assert.ok(uniform.some((v,i)=>Math.abs(v-degree[i])>.01));assert.ok(goal.some((v,i)=>Math.abs(v-degree[i])>.01));assert.deepEqual(JSON.parse(JSON.stringify(messages.filter(m=>m.type==='ready').at(-1).goals)),[{id:'native_goal',label:'native_goal'}]);cases++;console.log('PASS degree uniform and explicit native goal weights change charge without inferred goals');
  await send({type:'configure',options:base,request:900});const accepted=messages.find(m=>m.request===900).options;await send({type:'configure',options:{damping:.2,linkDistance:NaN},request:901});assert.equal(messages.find(m=>m.request===901).type,'error');await send({type:'configure',options:{},request:902});assert.equal(messages.find(m=>m.request===902).options.damping,accepted.damping,'invalid partial config remains atomic');cases++;console.log('PASS invalid force config is rejected atomically');
  const before=JSON.stringify(pair);await init(pair);await send({type:'configure',options:base});await send({type:'drag',id:'n0',x:100,y:0});
  for(let i=0;i<30;i++){await send({type:'drag',id:'n0',x:100+i,y:0});await send({type:'viewport',level:0,rect:pair.bounds,request:1000+i});const v=messages.find(m=>m.request===1000+i);assert.ok(v&&!v.cancelled,'camera responds without waiting for cooling');assert.equal(v.counters.stableViewport,true);assert.equal(v.counters.rawSpatialBuilds,0,'overview record drag never builds raw geometry');if(i%3===0&&tasks.size)one();}
  const tickStart=messages.length;await send({type:'pause'});drain();const stopped=messages.filter(m=>m.type==='physics').length;await send({type:'resume'});assert.ok(tasks.size>0);one();assert.ok(messages.filter(m=>m.type==='physics').length>stopped);await send({type:'drag',id:'n0',x:null,y:null});drain();await send({type:'viewport',level:3,rect:pair.bounds,request:1100});const settled=messages.find(m=>m.request===1100);assert.equal(settled.counters.stableViewport,false);assert.equal(settled.counters.totalEdges,2);assert.equal(settled.counters.representedCrossingEdges,2);assert.ok(messages.slice(tickStart).some(m=>m.type==='physics'&&m.settled));assert.equal(JSON.stringify(pair),before);cases++;console.log('PASS sustained 30 pointer packets serve camera snapshots immediately and pause resume release commit exact geometry');
  await init(pair);await send({type:'drag',id:'n0',x:null,y:null});assert.equal(tasks.size,0,'click-only release does not start physics');await send({type:'viewport',level:0,rect:pair.bounds,request:1200});assert.equal(messages.find(m=>m.request===1200).counters.rawSpatialBuilds,0);cases++;console.log('PASS click-only release does not start cold indexing or physics');
  const projection=fixture(4);projection.nodes[0].summary='native summary';projection.nodes[0].display_kind='观测';projection.nodes[0].color='#aabbcc';projection.nodes[0].shape='hexagon';projection.nodes[0].outline={state:'neutral'};projection.nodes[0].goal_weights={goal:0.6};projection.edges=[[0,1,0,0,0],[0,2,1,1,1]];projection.semantics=['source_binding','snapshot_contains'];projection.edge_types=['provenance','membership'];projection.source.edge_count=2;const core=Core.create(projection),full=core.viewport(3,projection.bounds),filtered=core.viewport(3,projection.bounds,3500,3500,{showOrphans:false,membership:false});assert.equal(full.counters.totalEdges,filtered.counters.totalEdges);assert.equal(filtered.edges.length,1);assert.equal(filtered.edges[0].semantic,'source_binding','membership filter retains provenance');assert.equal(filtered.points.some(p=>p.id==='n3'),false);const p=full.points.find(p=>p.id==='n0');for(const key of ['summary','display_kind','color','shape','outline','goal_weights'])assert.deepEqual(p[key],projection.nodes[0][key]);assert.equal(p.clusterPath.length,3);assert.equal(core.find('native summary').total,1);cases++;console.log('PASS presentation projection and display filters preserve full raw search identities totals and provenance');
}
async function workerPauseRegressions(){
  const fs=require('node:fs'),vm=require('node:vm'),zlib=require('node:zlib'),path=require('node:path');
  const py=fs.readFileSync(path.join(__dirname,'../scripts/rds_hypergraph_view.py'),'utf8'),d3=py.match(/D3_BUNDLE = r'{3}([\s\S]*?)'{3}/)[1];
  const messages=[],tasks=new Map();let taskId=0,clock=0;
  const ctx=vm.createContext({Blob,Response,DecompressionStream,atob,Uint8Array,Uint32Array,Float32Array,ArrayBuffer,performance:{now:()=>clock},setTimeout:fn=>{const id=++taskId;tasks.set(id,fn);return id;},clearTimeout:id=>tasks.delete(id),setInterval:()=>++taskId,clearInterval(){},self:{postMessage:m=>messages.push(m)}});
  vm.runInContext(d3,ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../scripts/hypergraph_archive/worker.js'),'utf8'),ctx);
  const send=data=>ctx.self.onmessage({data}),init=data=>send({type:'init',compressed:zlib.gzipSync(JSON.stringify(data)).toString('base64')});
  function one(){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}
  function drain(){let count=0;while(tasks.size&&count++<1500)one();assert.ok(count<1500,'production worker commits and cools within the bounded fixture');}

  const small=fixture(4);await init(small);await send({type:'configure',options:{flowStrength:0,groupStrength:0,centerStrength:0,repelStrength:0,edgeRepulsion:0}});
  assert.equal(tasks.size,0,'opening/configuring the graph must not silently start a layout');
  const coldStart=messages.length;await send({type:'reheat',id:'n0'});assert.ok(tasks.size>0,'explicit relayout seeds a first simulation without dragging');let coldLoops=0;while(!messages.slice(coldStart).some(m=>m.type==='physics')&&tasks.size&&coldLoops++<20)one();
  const coldPacket=messages.slice(coldStart).find(m=>m.type==='physics');assert.ok(coldPacket&&coldPacket.steps===1&&coldPacket.nodes<=512&&coldPacket.springs<=1024);
  await send({type:'viewport',level:0,rect:small.bounds,request:1901});assert.equal(messages.find(m=>m.request===1901).counters.rawSpatialBuilds,0,'the first explicit layout does not force raw indexing');await send({type:'pause'});drain();
  cases++;console.log('PASS first explicit relayout starts bounded physics without a prior drag or raw index');

  await init(small);await send({type:'configure',options:{flowStrength:0,groupStrength:0,centerStrength:0,repelStrength:0,edgeRepulsion:0,linkStrength:1,linkDistance:80}});
  await send({type:'drag',id:'n0',x:100,y:0});await send({type:'pause'});drain();
  const stopped=messages.length;await send({type:'configure',options:{damping:.2}});assert.equal(tasks.size,0,'changing force settings while paused preserves the stopped layout');
  await send({type:'resume'});assert.ok(tasks.size>0);let resumeLoops=0;while(!messages.slice(stopped).some(m=>m.type==='physics')&&tasks.size&&resumeLoops++<20)one();
  const resumed=messages.slice(stopped).find(m=>m.type==='physics'),offset=resumed.ids.indexOf('n0')*2,coords=new Float32Array(resumed.buffer);
  assert.ok(offset>=0);assert.ok(Math.abs(coords[offset]-100)>1e-4||Math.abs(coords[offset+1])>1e-4,'pause releases a held drag anchor; resume must not leave its fixed coordinates trapped');
  await send({type:'pause'});drain();cases++;console.log('PASS pausing a held drag releases the anchor and paused configuration cannot restart it');

  const large=fixture(2504),before=JSON.stringify(large);await init(large);
  await send({type:'drag',id:'c0',x:1200,y:0});await send({type:'pause'});await send({type:'resume'});await send({type:'pause'});
  const finalPause=messages.length;assert.ok(tasks.size>0,'the large aggregate fixture actually enters yielded commit');drain();
  assert.equal(messages.slice(finalPause).filter(m=>m.type==='physics').length,0,'a newer pause cancels the queued resume instead of restarting physics after commit');
  assert.equal(messages.filter(m=>m.type==='physics').at(-1).paused,true);
  await send({type:'viewport',level:0,rect:large.bounds,request:1900});assert.ok(messages.find(m=>m.request===1900),'committed paused geometry remains browsable');
  assert.equal(JSON.stringify(large),before);assert.equal(messages.filter(m=>m.type==='error').length,0);
  cases++;console.log('PASS final pause supersedes an older queued resume during yielded aggregate commit');
}
async function workerContinuityChecks(){
  const fs=require('node:fs'),vm=require('node:vm'),zlib=require('node:zlib'),path=require('node:path'),py=fs.readFileSync(path.join(__dirname,'../scripts/rds_hypergraph_view.py'),'utf8'),d3=py.split("D3_BUNDLE = r'''")[1].split("'''")[0];
  const tasks=new Map(),messages=[];let next=0,clock=0;
  const ctx=vm.createContext({Blob,Response,DecompressionStream,atob,Uint8Array,Uint32Array,Float32Array,ArrayBuffer,performance:{now:()=>clock},setTimeout:fn=>{const id=++next;tasks.set(id,fn);return id;},clearTimeout:id=>tasks.delete(id),setInterval:()=>++next,clearInterval(){},self:{postMessage:m=>messages.push(m)}});
  vm.runInContext(d3,ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../scripts/hypergraph_archive/worker.js'),'utf8'),ctx);const send=data=>ctx.self.onmessage({data});
  function one(){const [id,fn]=tasks.entries().next().value;tasks.delete(id);clock+=35;fn();}
  function drain(){let loops=0;while(tasks.size&&loops++<1500)one();assert.ok(loops<1500);}
  async function init(data){await send({type:'init',compressed:zlib.gzipSync(JSON.stringify(data)).toString('base64')});await send({type:'configure',options:{repelStrength:0,centerStrength:0,groupStrength:0,flowStrength:0,edgeRepulsion:0,linkStrength:1,linkDistance:80,membership:true,relations:{dependency:{mode:'attract',strength:1},source:{mode:'none',strength:1}}}});}
  async function drag(id,x,steps=1){const start=messages.length;await send({type:'drag',id,x,y:0});let loops=0;while((messages.slice(start).filter(m=>m.type==='physics').at(-1)?.steps||0)<steps&&tasks.size&&loops++<1500)one();assert.ok(loops<1500);return messages.slice(start).filter(m=>m.type==='physics').at(-1);}
  const chain=fixture(3);chain.nodes.forEach((n,i)=>{n.x=i*100;n.y=0;n.type='claim';});chain.edges=[[0,1,0,0,0],[1,2,0,0,1]];
  chain.edge_types=['membership'];await init(chain);await send({type:'configure',options:{membership:false}});const isolated=await drag('n0',500);assert.deepEqual(Array.from(isolated.ids),['n0']);assert.equal(isolated.springs,0);assert.equal(isolated.edges,1);await send({type:'pause'});drain();cases++;console.log('PASS hidden membership cannot take force slots while original incidence remains indexed');
  chain.edge_types=['and_premise'];await init(chain);await drag('n0',500);const switched=await drag('n1',700);assert.ok(switched.ids.includes('n2'));await send({type:'drag',id:'n0',x:null,y:null});one();const current=messages.filter(m=>m.type==='physics').at(-1);assert.equal(new Float32Array(current.buffer)[current.ids.indexOf('n1')*2],700);await send({type:'pause'});drain();cases++;console.log('PASS adjacent seed changes rebuild their own neighborhood and ignore old releases');
  const cap=fixture(514);cap.nodes.forEach(n=>n.type='claim');cap.semantics=['provenance','dependency'];cap.edge_types=['source_binding','and_premise'];cap.edges=Array.from({length:512},(_,i)=>[0,i+1,0,0,i]);cap.edges.push([0,513,1,1,512]);await init(cap);const bounded=await drag('n0',500);assert.deepEqual(Array.from(bounded.ids),['n0','n513']);assert.equal(bounded.edges,513);await send({type:'pause'});drain();cases++;console.log('PASS no-force sources cannot exhaust the bounded dependency neighborhood');
  const mixed=fixture(4);mixed.nodes.forEach(n=>n.type='claim');mixed.semantics=['A','B'];mixed.edge_types=['and_premise'];mixed.edges=[[0,2,0,0,0],[0,2,1,0,1],[0,2,1,0,2]];
  async function aggregate(reverse,groupStrength=0){const data=structuredClone(mixed);if(reverse)data.edges.reverse();await init(data);await send({type:'configure',options:{groupStrength,relations:{'A|and_premise':{mode:'attract',strength:2},'B|and_premise':{mode:'repel',strength:.5}}}});const p=await drag('c0',-200,12),x=new Float32Array(p.buffer)[p.ids.indexOf('c3')*2];assert.equal(p.springs,2);await send({type:'pause'});drain();return x;}
  const forward=await aggregate(false),reverse=await aggregate(true),cohesion=await aggregate(false,.15);assert.ok(Math.abs(forward-reverse)<.001);assert.ok(Math.abs(forward-cohesion)>1);cases++;console.log('PASS mixed aggregate forces are insertion independent and use actual group cohesion');
  async function distance(linkDistance){const d=fixture(2);d.nodes.forEach((n,i)=>{n.type='claim';n.x=i*10000;n.y=0;});d.edge_types=['and_premise'];d.edges=[[0,1,0,0,0]];await init(d);await send({type:'configure',options:{linkDistance}});const p=await drag('n0',100,12),x=new Float32Array(p.buffer)[p.ids.indexOf('n1')*2];await send({type:'pause'});drain();return x;}
  assert.ok(Math.abs(await distance(40)-await distance(80))>100);cases++;console.log('PASS link-distance controls affect long archived spans instead of being masked by a floor');
  const large=fixture(2504);large.nodes.forEach(n=>n.type='claim');large.edges=[[0,1500,0,0,0]];await init(large);await drag('c0',1200);await send({type:'drag',id:'c0',x:null,y:null});const start=messages.length;await send({type:'configure',options:{membership:false}});drain();assert.equal(messages.slice(start).filter(m=>m.type==='error').length,0);await send({type:'locate',index:0,request:1701});const locate=messages.find(m=>m.request===1701);await send({type:'cluster',index:0,request:1702});const bounds=messages.find(m=>m.request===1702);assert.ok(locate.x>=bounds.memberBounds[0]&&locate.x<=bounds.memberBounds[2]);
  await drag('c0',1300);await send({type:'reheat',id:'n0'});drain();const reheated=messages.filter(m=>m.type==='physics').at(-1);assert.ok(reheated.ids.includes('n0')&&reheated.settled);assert.equal(messages.filter(m=>m.type==='error').length,0);cases++;console.log('PASS released aggregate configuration and raw reheat survive yielded commit without trapping anchors');
  const moved=fixture(4);moved.edges=[[0,2,0,0,0]];await init(moved);await send({type:'configure',options:{linkStrength:0}});
  await drag('c0',1200);const reheatStart=messages.length;await send({type:'reheat',id:'c0'});one();
  const reheatedCoarse=messages.slice(reheatStart).find(m=>m.type==='physics'),liveX=new Float32Array(reheatedCoarse.buffer)[reheatedCoarse.ids.indexOf('c0')*2];
  assert.equal(liveX,1200,'coarse relayout releases the current simulated position, not the archived cluster');await send({type:'pause'});drain();cases++;console.log('PASS coarse reheat retains uncommitted live aggregate coordinates');
  const collision=fixture(2);collision.nodes.forEach(n=>{n.source_id=null;n.group=null;});collision.semantics=['A|B','A'];collision.edge_types=['and_premise','B|and_premise'];collision.edges=[[0,1,0,0,0],[0,1,1,1,1]];await init(collision);
  const catalog=messages.filter(m=>m.type==='ready').at(-1).relationCatalog;assert.equal(new Set(Array.from(catalog,r=>r.key)).size,2);assert.ok(catalog.every(r=>r.legacyKey===null));
  await send({type:'configure',options:{relations:{'A|B|and_premise':{mode:'none',strength:1},[JSON.stringify(['A|B','and_premise'])]:{mode:'none',strength:1},[JSON.stringify(['A','B|and_premise'])]:{mode:'attract',strength:1}}}});
  const separate=await drag('n0',1200);assert.equal(separate.springs,1,'tuple settings affect only the exact semantic/type identity');await send({type:'viewport',level:3,rect:collision.bounds,request:1767});const displayed=messages.find(m=>m.request===1767);assert.equal(new Set(Array.from(displayed.edges,e=>e.relationKey)).size,2);await send({type:'pause'});drain();cases++;console.log('PASS delimiter-colliding relations retain separate display settings and force identities');
  const aliasCollision=fixture(2);aliasCollision.semantics=['dependency|x','["dependency'];aliasCollision.edge_types=['z','x","z"]'];aliasCollision.edges=[[0,1,0,0,0],[0,1,1,1,1]];await init(aliasCollision);
  const modernKey=JSON.stringify(['dependency|x','z']),aliasCatalog=messages.filter(m=>m.type==='ready').at(-1).relationCatalog;assert.equal(aliasCatalog.find(r=>r.semantic==='["dependency').legacyKey,null,'a legacy alias cannot be another exact tuple key');
  await send({type:'configure',options:{relations:{[modernKey]:{mode:'none',strength:1}}}});const aliasSeparate=await drag('n0',1200);assert.equal(aliasSeparate.springs,1,'a modern override cannot leak through a legacy alias');await send({type:'pause'});drain();cases++;console.log('PASS legacy aliases cannot shadow modern tuple identities or family defaults');


  async function authoredCohesion(authored,coarse,mixed=false){const data=fixture(4);data.nodes.forEach((n,i)=>{n.source_id=mixed==='source'&&i!==2?'original-run':null;n.group='type:claim';n.cohesion_group=authored&&!(mixed&&i===2)&&mixed!=='source'?'type:claim':null;n.type='claim';});data.edges=[[0,2,0,0,0]];await init(data);await send({type:'configure',options:{linkStrength:0,groupStrength:.15}});const packet=await drag(coarse?'c0':'n0',1200,12),id=coarse?'c3':'n2',x=new Float32Array(packet.buffer)[packet.ids.indexOf(id)*2];await send({type:'pause'});drain();return x;}
  for(const coarse of [false,true]){const isolated=await authoredCohesion(false,coarse),authored=await authoredCohesion(true,coarse);assert.equal(isolated,coarse?600:0);assert.equal(await authoredCohesion(true,coarse,true),isolated,'mixed authored and ungrouped members cannot inherit cohesion');assert.equal(await authoredCohesion(false,coarse,'source'),isolated,'mixed attributed and unattributed members cannot inherit a source');assert.ok(Math.abs(authored-isolated)>1,'explicit authored groups still transmit displacement');}cases++;console.log('PASS synthetic display buckets exert no raw or aggregate cohesion while authored type-prefixed groups do');
  async function namespacedCohesion(mode,coarse){const data=fixture(4);data.nodes.forEach((n,i)=>{const source=mode==='source'||mode==='cross'&&i<2;n.source_id=source?'same-label':null;n.group='type:claim';n.cohesion_group=source?null:'same-label';n.type='claim';});data.edges=[[0,2,0,0,0]];await init(data);await send({type:'configure',options:{linkStrength:0,groupStrength:.15}});const packet=await drag(coarse?'c0':'n0',1200,12),id=coarse?'c3':'n2',x=new Float32Array(packet.buffer)[packet.ids.indexOf(id)*2];await send({type:'pause'});drain();return x;}
  for(const coarse of [false,true]){const baseline=coarse?600:0;assert.equal(await namespacedCohesion('cross',coarse),baseline,'equal source/group labels cannot transmit displacement between distinct identities');for(const mode of ['source','group'])assert.ok(Math.abs(await namespacedCohesion(mode,coarse)-baseline)>1,'matching typed identities retain cohesion');}cases++;console.log('PASS source and authored-group namespaces remain distinct in raw and aggregate forces with positive controls');

}
async function workerSegmentChecks(){
  const fs=require('node:fs'),vm=require('node:vm'),zlib=require('node:zlib'),path=require('node:path'),py=fs.readFileSync(path.join(__dirname,'../scripts/rds_hypergraph_view.py'),'utf8'),d3=py.match(/D3_BUNDLE = r'{3}([\s\S]*?)'{3}/)[1],worker=fs.readFileSync(path.join(__dirname,'../scripts/hypergraph_archive/worker.js'),'utf8');
  async function run(strength,own){const data=fixture(4);data.nodes.forEach((n,i)=>{n.x=[1000,0,400,200][i];n.y=[1000,0,0,8][i];n.type=i===1?'hyperedge':'claim';});data.edges=[[0,1,0,0,0],[0,2,0,0,1],[0,3,0,0,2],[1,2,0,0,3]];if(own==='budget')for(let i=0;i<1030;i++)data.edges.push([0,1,0,0,data.edges.length]);if(own){data.semantics.push('OWN');data.edge_types.push(own==='source'?'source_binding':'and_premise');data.edges.push([3,1,1,3,data.edges.length]);}data.source.edge_count=data.edges.length;const tasks=new Map(),messages=[];let id=0,clock=0;const ctx=vm.createContext({Blob,Response,DecompressionStream,atob,Uint8Array,Uint32Array,Float32Array,ArrayBuffer,performance:{now:()=>clock},setTimeout:fn=>{const key=++id;tasks.set(key,fn);return key;},clearTimeout:key=>tasks.delete(key),setInterval:()=>++id,clearInterval(){},self:{postMessage:m=>messages.push(m)}});vm.runInContext(d3,ctx);vm.runInContext(worker,ctx);const send=data=>ctx.self.onmessage({data});await send({type:'init',compressed:zlib.gzipSync(JSON.stringify(data)).toString('base64')});await send({type:'configure',options:{repelStrength:0,flowStrength:0,groupStrength:0,linkStrength:0,centerStrength:0,edgeRepulsion:strength,edgeClearance:35,relations:own==='none'?{'OWN|and_premise':{mode:'none',strength:1}}:own==='zero'?{'OWN|and_premise':{mode:'attract',strength:0}}:{}}});await send({type:'drag',id:'n0',x:1000,y:1000});let loops=0;while((messages.filter(m=>m.type==='physics').at(-1)?.steps||0)<12&&tasks.size&&loops++<100){const [key,fn]=tasks.entries().next().value;tasks.delete(key);clock+=35;fn();}const packet=messages.filter(m=>m.type==='physics').at(-1);assert.ok(packet&&packet.nodes<=512&&packet.springs<=1024);const offset=packet.ids.indexOf('n3')*2,coords=new Float32Array(packet.buffer);await send({type:'pause'});return {x:coords[offset],y:coords[offset+1],errors:messages.filter(m=>m.type==='error')};}
  const neutral=await run(0,false),repelled=await run(.6,false),own=await run(.6,true);assert.ok(Math.hypot(200,8)>35,'nonmember fixture is far outside the hub circle');assert.equal(neutral.y,8);assert.ok(repelled.y>neutral.y+1,'whole incidence segment repels a nonmember far from the hub');assert.equal(own.x,200,'own member is exempt from the same nearby segment');assert.equal(own.y,8);assert.equal(neutral.errors.length+repelled.errors.length+own.errors.length,0);cases++;console.log('PASS actual local incidence segments repel unrelated nodes far from hubs and exempt own members');
  for(const mode of ['none','zero','budget']){const own=await run(.6,mode);assert.equal(own.x,200,mode+' preserves true AND membership despite spring filtering');assert.equal(own.y,8);assert.equal(own.errors.length,0);}const provenance=await run(.6,'source');assert.ok(provenance.y>8,'a provenance binding does not grant AND-member exemption');cases++;console.log('PASS full AND membership survives none zero and spring caps while provenance remains nonmember');
}
async function explorerChecks(){
  const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),ui=require('../scripts/hypergraph_archive/explorer.js');
  const source=fs.readFileSync(path.join(__dirname,'../scripts/hypergraph_archive/explorer.js'),'utf8');
  const nodes=[{id:'n0'},{id:'n1'}],link={source:nodes[0],target:nodes[1],rds:{},rendered:false},elements=new Map();
  const ctx=vm.createContext({performance:{now:()=>0},paintLegend(){},ArchivePresentation:ui,options:ui.defaults(),lastPhysics:new Map(),fitScale:1,growthFrame:null,selected:null,currentScene:null,activeDrag:null,fadeTimer:null,ready:true,view:new Map(),topology:'',showNames:false,api:{viewport:{},totals:{nodes:2,edges:1}},host:{dataset:{}},color:()=>0,g:{scale:1,panX:0,panY:0,width:100,height:100,nodeLookup:new Map(nodes.map(n=>[n.id,n])),links:[link],setData(){},changed(){}},cancelGrowth(){},document:{querySelectorAll:()=>[]},$:id=>{if(!elements.has(id))elements.set(id,{});return elements.get(id);}});
  vm.runInContext(source.match(/  const relationStyles=([^;]+);/)[0]+'\n'+source.slice(source.indexOf('  function pointStyle('),source.indexOf('  function cancelGrowth(')),ctx);
  for(const family of ['other','mixed','source','dependency','history']){
    ctx.scene={level:3,points:nodes.map((n,index)=>({id:n.id,index,x:index*10,y:0,type:'claim',raw:true,label:'可读名称',status:'UNKNOWN'})),edges:[{source:'n0',target:'n1',family,count:7,index:0}],counters:{visibleNodes:2}};
    vm.runInContext('paint(scene,[0,0,100,100])',ctx);assert.equal(link.rds.relation,family);
    if(family==='other'||family==='mixed')assert.equal(link.rds.dash,false,'unknown or mixed relations retain a neutral display');
  }
  cases++;console.log('PASS actual paint preserves unknown mixed and known relation identities');
  ctx.options.relations['A|and_premise']={color:'#ff0000',width:2,dash:'dashed'};
  ctx.options.relations['B|and_premise']={color:'#0000ff',width:1,dash:'dotted'};
  ctx.scene.edges=[{source:'n0',target:'n1',family:'dependency',relationKey:'B|and_premise',count:1},{source:'n0',target:'n1',family:'dependency',relationKey:'A|and_premise',count:1}];
  vm.runInContext('paint(scene,[0,0,100,100])',ctx);const composite=JSON.stringify(link.rds);
  assert.deepEqual(Array.from(link.rds.relationKeys),['A|and_premise','B|and_premise']);assert.equal(link.rds.color,'#800080');assert.equal(link.rds.width,2);assert.equal(link.rds.pattern,'solid');
  assert.deepEqual(Array.from(link.rds.relationStyles,s=>s.color),['#ff0000','#0000ff']);ctx.scene.edges.reverse();vm.runInContext('paint(scene,[0,0,100,100])',ctx);assert.equal(JSON.stringify(link.rds),composite);
  cases++;console.log('PASS actual endpoint composition retains parallel style identities with deterministic composite appearance');
  const sent=[],fctx=vm.createContext({ArchivePresentation:ui,options:ui.defaults(),relationCatalog:[{family:'source',key:'bound|source_binding'}],persist(){},optionTimer:null,setTimeout:fn=>{fn();return 1;},clearTimeout(){},worker:{postMessage:m=>sent.push(m)}});
  vm.runInContext(source.match(/  const relationStyles=([^;]+);/)[0]+'\n'+source.slice(source.indexOf('  function applyForces('),source.indexOf('  function reheatView(')),fctx);
  vm.runInContext('applyForces()',fctx);assert.equal(sent.at(-1).options.relations.source.strength,.35);assert.equal(sent.at(-1).options.relations.history.strength,.15);assert.equal(sent.at(-1).options.relations['bound|source_binding'].strength,.35);
  fctx.options.relations.source={strength:.6};fctx.options.relations['bound|source_binding']={mode:'repel',strength:.2};vm.runInContext('applyForces()',fctx);assert.equal(sent.at(-1).options.relations.source.strength,.6);assert.equal(sent.at(-1).options.relations['bound|source_binding'].mode,'repel');assert.equal(sent.at(-1).options.relations['bound|source_binding'].strength,.2);
  cases++;console.log('PASS actual initial force configuration retains worker family defaults and explicit user overrides');
  const packet=(ids,values,aggregateLevel=null)=>({ids,buffer:new Float32Array(values).buffer,aggregateLevel});let pendingPhysics=ui.retainPhysics(new Map(),packet(['n0','n1'],[50,60,70,80]));pendingPhysics=ui.retainPhysics(pendingPhysics,packet(['n2'],[90,100]));assert.equal(pendingPhysics.get('n0').x,50);assert.equal(pendingPhysics.get('n1').y,80);assert.equal(pendingPhysics.get('n2').x,90);pendingPhysics=ui.retainPhysics(pendingPhysics,packet(['n0'],[55,65]));assert.equal(pendingPhysics.size,3);assert.equal(pendingPhysics.get('n0').x,55);pendingPhysics=ui.retainPhysics(pendingPhysics,packet(['c0'],[500,600],0));assert.equal(pendingPhysics.size,1);assert.equal(pendingPhysics.has('n0'),false);
  cases++;console.log('PASS disjoint raw physics packets retain pending positions and aggregate publication starts a fresh shift');

  let renderedData;
  ctx.g.setData=data=>{renderedData=data;ctx.g.nodeLookup=new Map(Object.keys(data.nodes).map(id=>[id,{id}]));ctx.g.links=data.links.map(([a,b,rds])=>({source:ctx.g.nodeLookup.get(a),target:ctx.g.nodeLookup.get(b),rds,rendered:false}));};
  ctx.scene={level:3,points:[{id:'n0',index:0,x:10,y:15,type:'claim',raw:true,label:'真实声明',status:'UNKNOWN',shape:'circle'}],anchors:[{id:'a0',x:0,y:30,anchor:true},{id:'a1',x:100,y:60,anchor:true}],edges:[{source:'a0',target:'a1',family:'dependency',summary:true,count:120}],counters:{visibleNodes:1}};
  vm.runInContext('paint(scene,[0,0,100,100])',ctx);
  assert.deepEqual([...ctx.view.keys()],['n0'],'connection helpers cannot enter record inspection, hover or growth');
  assert.equal(renderedData.nodes.a0.label,'');assert.deepEqual(Object.keys(renderedData.nodes.a0.rds).sort(),['anchor','radius']);assert.equal(ctx.g.nodeLookup.get('a0').rdsHidden,undefined,'geometry must not hide its incident link');
  assert.equal(ctx.g.nodeLookup.get('a0').x,0);assert.equal(ctx.g.nodeLookup.get('a1').y,60);assert.equal(ctx.g.links[0].rds.summary,true);assert.equal(ctx.g.links[0].rds.arrow,false);assert.ok(ctx.g.links[0].rds.opacity<=.12);assert.equal(ctx.g.nodeLookup.get('n0').x,10);
  cases++;console.log('PASS actual paint keeps connection geometry separate from readable records and directed relations');
  const fadeTasks=new Map();ctx.fadeTimer=null;ctx.setTimeout=fn=>{const id=fadeTasks.size+1;fadeTasks.set(id,fn);return id;};ctx.clearTimeout=id=>fadeTasks.delete(id);ctx.g.nodeLookup.get('n0').x=30;ctx.g.nodeLookup.get('n0').y=45;
  ctx.scene={level:3,points:[{id:'v3:32:0,0',type:'density',x:20,y:20,label:'附近记录',count:2}],edges:[],counters:{visibleNodes:2}};
  vm.runInContext('paint(scene,[0,0,100,100])',ctx);assert.equal(ctx.g.nodeLookup.get('ghost:n0').x,30);assert.equal(ctx.g.nodeLookup.get('ghost:n0').y,45);assert.equal(ctx.g.nodeLookup.get('ghost:n0').label,'');assert.equal(ctx.g.nodeLookup.get('ghost:n0').rds.labelAllowed,false);assert.deepEqual([...ctx.view.keys()],['v3:32:0,0']);assert.equal(fadeTasks.size,1);assert.ok(ctx.g.nodeLookup.size<=3500);
  const clean=fadeTasks.values().next().value;fadeTasks.clear();clean();assert.equal(ctx.g.nodeLookup.has('ghost:n0'),false);cases++;console.log('PASS transition ghosts use live coordinates and expire outside inspection and label budgets');
  const pending=[],painted=[];let clock=1000;
  const qctx=vm.createContext({performance:{now:()=>clock},options:ui.defaults(),$:()=>({value:''}),ready:true,fitScale:1,level:0,lastQuery:0,lastSignature:'',pendingQuery:false,queuedView:null,viewportVersion:0,initialGrowth:false,queryTimer:null,api:{},g:{scale:1,panX:0,panY:0,width:100,height:100},request:(type,value)=>new Promise(resolve=>pending.push({value,resolve})),paint:(m,r)=>painted.push({m,r}),fail:error=>{throw error;},setTimeout:()=>1,clearTimeout(){}});
  vm.runInContext(source.slice(source.indexOf('  function currentLevel('),source.indexOf('  function pattern(')),qctx);
  vm.runInContext('query(true)',qctx);
  for(let i=0;i<20;i++){
    clock+=80;qctx.g.panX+=5;vm.runInContext('query()',qctx);assert.equal(pending.length,i+1,'only one request is outstanding');
    pending[i].resolve({level:0,counters:{}});await Promise.resolve();await Promise.resolve();assert.equal(painted.length,i+1,'completed scenes remain visible while moving');
  }
  const before=pending.length;
  for(let i=0;i<50;i++){clock+=80;qctx.g.panX+=5;vm.runInContext('query()',qctx);}
  assert.equal(pending.length,before,'camera bursts do not queue extra worker work');
  pending.at(-1).resolve({level:0,counters:{}});await Promise.resolve();await Promise.resolve();assert.equal(pending.length,before+1);
  assert.equal(pending.at(-1).value.rect[0],-qctx.g.panX-80,'the newest camera replaces intermediate views');
  pending.at(-1).resolve({level:0,counters:{}});await Promise.resolve();await Promise.resolve();assert.equal(painted.length,22);
  cases++;console.log('PASS actual explorer keeps continuous pan visible and coalesces camera bursts');
}
async function explorerParityRegressions(){
  const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),ui=require('../scripts/hypergraph_archive/explorer.js');
  const source=fs.readFileSync(path.join(__dirname,'../scripts/hypergraph_archive/explorer.js'),'utf8');
  const packets=[],timers=new Map();let nextTimer=0;
  const config=vm.createContext({ArchivePresentation:ui,options:ui.defaults(),optionTimer:null,persist(){},clearTimeout:id=>timers.delete(id),setTimeout:fn=>{const id=++nextTimer;timers.set(id,fn);return id;},worker:{postMessage:m=>packets.push(m)},paused:false});
  vm.runInContext(source.match(/  const relationStyles=([^;]+);/)[0]+'\nconst relationCatalog=[];',config);
  vm.runInContext(source.slice(source.indexOf('  function applyForces('),source.indexOf('  function flushDrag(')),config);
  for(const mode of ['uniform','degree','goal']){
    config.options.sizeMode=mode;config.options.goal='native-goal';vm.runInContext('applyForces()',config);
    assert.equal(timers.size,1);const [id,fn]=timers.entries().next().value;timers.delete(id);fn();
    const packet=packets.filter(p=>p.type==='configure').at(-1);assert.equal(packet.options.weightMode,mode);assert.equal(packet.options.goal,'native-goal');
  }
  cases++;console.log('PASS actual UI configure preserves uniform degree and native goal modes');

  const actions=new Map(),elements=new Map();const element=()=>({append(){},replaceChildren(){},setAttribute(){},addEventListener(){}});
  const style=vm.createContext({ArchivePresentation:ui,options:ui.defaults(),api:{goals:[]},relationCatalog:[{key:'original_dependency|and_premise',semantic:'original_dependency',type:'and_premise',family:'dependency'}],relationPage:0,section:element,checkbox(){},slider(){},select(parent,label,value,entries,action){actions.set(label,action);},text:element,button:element,pager(){},appearance(){},applyForces(){},reheatView(){},persist(){},$:id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id);}});
  vm.runInContext(source.match(/  const relationStyles=([^;]+);/)[0]+'\n'+source.slice(source.indexOf('  function pointStyle('),source.indexOf('  function restoreEdges('))+'\n'+source.slice(source.indexOf('  function settingsUI('),source.indexOf('  function restoreSettings(')),style);
  vm.runInContext('settingsUI()',style);actions.get('依赖作用')('none');
  assert.equal(style.options.relations.dependency.mode,'none');
  assert.equal(vm.runInContext("edgeStyle({family:'dependency',relationKey:'original_dependency|and_premise'}).mode",style),'none','opening individual relation controls must not shadow family settings');
  actions.get('and_premise作用')('repel');
  assert.equal(vm.runInContext("edgeStyle({family:'dependency',relationKey:'original_dependency|and_premise'}).mode",style),'repel','an explicit individual override still takes precedence');
  cases++;console.log('PASS rendered relation controls inherit families until explicitly overridden');

  for(const changed of ['showOrphans','membership','searchFilter']){
    const pending=[];let clock=1000;
    const context=vm.createContext({performance:{now:()=>clock},options:ui.defaults(),$:()=>({value:'needle'}),ready:true,fitScale:1,level:0,lastQuery:0,lastSignature:'',pendingQuery:false,queuedView:null,viewportVersion:0,initialGrowth:false,queryTimer:null,api:{},g:{scale:1,panX:0,panY:0,width:100,height:100},request:(type,value)=>new Promise(resolve=>pending.push({value,resolve})),paint(){},fail:e=>{throw e;},setTimeout:()=>1,clearTimeout(){}});
    vm.runInContext(source.slice(source.indexOf('  function currentLevel('),source.indexOf('  function pattern(')),context);vm.runInContext('query(true)',context);
    context.options[changed]=!context.options[changed];vm.runInContext('query(true)',context);
    for(let frame=0;frame<8;frame++){clock+=17;vm.runInContext('query()',context);}
    pending[0].resolve({level:0,counters:{}});await Promise.resolve();await Promise.resolve();
    assert.equal(pending.length,2,'filter changes survive ordinary stationary camera frames: '+changed);
    const filters=pending[1].value.filters;
    assert.equal(changed==='searchFilter'?filters.query:filters[changed],changed==='searchFilter'?'needle':false);
    pending[1].resolve({level:0,counters:{}});await Promise.resolve();await Promise.resolve();
    cases++;console.log('PASS stationary pending camera retains '+changed+' changes');
  }

  const frames=new Map(),dragPackets=[];let nextFrame=0;const node={x:0,y:0};
  const drag=vm.createContext({paused:false,dragFrame:null,dragTarget:null,activeDrag:null,lastPhysics:new Map(),api:{},g:{nodeLookup:new Map([['n0',node]]),changed(){}},worker:{postMessage:m=>dragPackets.push(m)},requestAnimationFrame:fn=>{const id=++nextFrame;frames.set(id,fn);return id;},cancelAnimationFrame:id=>frames.delete(id)});
  vm.runInContext(source.slice(source.indexOf('  function flushDrag('),source.indexOf('  function makeWorker(')),drag);
  for(let x=0;x<100;x++){drag.target={id:'n0',x,y:5};vm.runInContext('sendDrag(target)',drag);}
  assert.equal(dragPackets.length,0);assert.equal(frames.size,1);assert.equal(node.x,99,'pointer movement updates the scene without waiting for the worker');
  vm.runInContext("sendDrag({id:'n0',x:null,y:null})",drag);
  assert.equal(frames.size,0);assert.deepEqual(dragPackets.map(p=>[p.id,p.x,p.y]),[['n0',99,5],['n0',null,null]],'the latest pointer must be flushed before releasing the anchor');
  vm.runInContext("sendDrag({id:'n0',x:null,y:null})",drag);assert.equal(dragPackets.length,2,'duplicate releases cannot reheat physics');
  drag.paused=true;vm.runInContext("sendDrag({id:'n0',x:200,y:5})",drag);assert.equal(dragPackets.length,2);assert.equal(frames.size,0);
  cases++;console.log('PASS UI drag bursts coalesce and release follows the newest coordinate exactly once');

  const first={id:'n0'},second={id:'n1'},third={id:'n2'},links=[{source:first,target:second,rds:{color:'#111111',width:1},archiveStyle:{color:'#111111',width:1}},{source:second,target:third,rds:{color:'#222222',width:1},archiveStyle:{color:'#222222',width:1}}];
  const card={hidden:false,replaceChildren(){},append(){}},selection=vm.createContext({inspectionVersion:0,selected:null,membershipSet:new Set(),membershipEdges:new Set(),g:{links,nodeLookup:new Map([['n0',first],['n1',second]]),changed(){}},api:{},card,kind:()=> '声明',shownStatus:()=> '未判定',button:()=>({}),text:()=>({}),pager(){},locate(){},request:async(type,m)=>type==='detail'?{node:{label:'节点 '+m.index,type:'claim'},entries:[],total:0,size:24,page:0}:{nodes:[m.index],edges:[]}});
  vm.runInContext(source.slice(source.indexOf('  function restoreEdges('),source.indexOf('  function paint('))+'\n'+source.slice(source.indexOf('  async function inspect('),source.indexOf('  async function locate(')),selection);
  await vm.runInContext('inspect(0)',selection);assert.equal(links[0].rds.width,2);assert.equal(links[1].rds.width,1);
  await vm.runInContext('inspect(1)',selection);vm.runInContext('clearSelection()',selection);
  assert.deepEqual(links.map(l=>[l.rds.color,l.rds.width]),[['#111111',1],['#222222',1]],'closing a second selection restores every original relation style');assert.equal(selection.g.rdsPinned,null);
  cases++;console.log('PASS selection A then B then close restores original relation styles');
}
workerChecks().then(workerParityChecks).then(workerPauseRegressions).then(workerContinuityChecks).then(workerSegmentChecks).then(explorerChecks).then(explorerParityRegressions).then(()=>console.log(JSON.stringify({pass:cases,fail:0,skip:0}))).catch(error=>{console.error(error);process.exitCode=1;});
